### ISSUE TITLE
appsody init fails (with Stack Check Requirement) with (at least) Docker 19.03.12

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#1008]
With docker 19.03.12 on macOS 10.15.2, you get the following (chose any stack)

```
appsody init incubator/nodejs-express
Checking stack requirements...
Appsody requirements met
[Error] The required version of Docker to use this stack is >= 17.09.0 - Please upgrade.
[Error] One or more technologies need upgrading to use this stack. Upgrades required: 1
```

What is really odd is this works in Docker 19.03.08.

I don't know what other environments may have this issue.

Here is my Docker config:

```
docker version
Client: Docker Engine - Community
 Azure integration  0.1.7
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by henrynash** [comment]
This is because the comparison with "Docker" is using the first version specified in the version info...i.e Azure integration =  0.1.7 (which it finds is less than 17.09.0)

**Comment by henrynash** [comment]
It would be probably better to use the format option with the `docker version` command, e.g.:

`docker version --format '{{.Server.Version}}'
`
which would return the correct `19.03.12`, rather than our current regex approach.

**Comment by balajikadambi** [comment]
I am seeing the same issue. When will this be fixed?

**Comment by henrynash** [comment]
Until this is merged, you could certainly use the PR that contains the fix attached. It would be great if you could confirm that this resolves the issue for you.
