### ISSUE TITLE
How to run 3 projects with appsody

### ISSUE THREAD

**Issue by oiricaud** [appsody/appsody#1010]
## Summary

I have 3 microservices that I wish to do `appsody run`
On microservice A, `appsody run` runs successfully, but if I run `appsody run` or microservice B or microservice C I get 

```bash
Running command: docker run --rm -p 8443:8443 -p 35729:35729 -p 5005:5005 -p 8080:8080 --name customer-ms-spring -u 501:20 -e "APPSODY_USER=501" -e "APPSODY_GROUP=20" -v "/Users/Oscar.Ricaud@ibm.com/Documents/gse-devops/github.com/oiricaud-customer-ms-spring/:/project/user-app" -v "/Users/Oscar.Ricaud@ibm.com/.m2/repository:/mvn/repository" -v appsody-controller-0.3.5:/.appsody -t --entrypoint /.appsody/appsody-controller docker.io/kabanero/java-spring-boot2:0.3 "--mode=run"
[Container] docker: Error response from daemon: driver failed programming external connectivity on endpoint customer-ms-spring (c1562cde1e5e209c470aa6ff59de74aece5eba5da0118a5dc4a3cafd209661bf): Bind for 0.0.0.0:35729 failed: port is already allocated.
[Error] Error in 'appsody run': exit status 125
```

How can I override the port #? I have tried `appsody run --port 8081:8081` but it doesn't replace the port number.

**Comment by neeraj-laad** [comment]
Yes, this is possible. You just need to use different host ports for different microservices, but use the same container port. 

- `--port 8081:8080` - manually specify port mapping
- `-P` - automatically use unused host port.

Please see https://appsody.dev/docs/faq/#7-why-does-my-appsody-project-on-macos-fail-with-the-error-address-already-in-use
