### ISSUE TITLE
Mixed case extract path directory causes problems on Linux systems

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#107]
**Describe the bug**
It's described here: https://github.com/eclipse/codewind/issues/33

**To Reproduce**
1. Create an appsody project that has MixedCase
2. Run appsody deploy
3. Observe that the extract directory still has MixedCase in it
4. See error if you are on RedHat or Ubuntu Linux

**Expected behavior**
No mixed case in the extract directory

**Actual behaviour**
The extract directory still has MixedCase, and that works ok on macOS and Windows - but causes Docker to fail the build on Linux.

**Environment Details (please complete the following information):**
 - OS: RHEL and Ubuntu

**If applicable please specify:**
 - CLI version: all 0.2.7 and prior
 - Stack you are using: any

**Screenshots**

**Additional context**

**Comment by kylegc** [comment]
Related to #73 and #88
