### ISSUE TITLE
appsody deploy fails when using -n option

### ISSUE THREAD

**Issue by bgower-ibm** [appsody/appsody#109]
**Describe the bug**
The -n flag is producing the wrong global option name on the kubectl command (`--name` instead of `--namespace`)

**To Reproduce**
e.g.
`appsody deploy -n default --push -t us.icr.io/bgower/demo`

**Expected behavior**
The kubectl command should apply the appsody service yaml.

**Actual behaviour**
```
Deploying your project to Kubernetes...
Running command: kubectl[apply -f /Users/bgower@us.ibm.com/codewind-workspace/demo2/appsody-service-606767950.yaml --name default]
[Error] kubectl apply failed: exit status 1 
```
Copying the failing command and manually changing to use `--namespace` works:
`kubectl apply -f /Users/bgower@us.ibm.com/codewind-workspace/demo2/appsody-service-606767950.yaml --namespace default`

**Environment Details (please complete the following information):**
 - OS: MacOS

**If applicable please specify:**
 - CLI version: 0.2.5
 - Stack you are using: Appsody Node.js Express template

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
@bgower-ibm Thanks for raising this issue. We will get to this soon.
