### ISSUE TITLE
Add docker run options for appsody run

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#116]
**Is your feature request related to a problem? Please describe.**
In order to enable more complex development environments, developers need the possibility to add more options for the `docker run` that is done internally. Setups that, for example, require more complex networking, would need to specify a `--network`. In order to be more flexible, we should allow to specify additional run arguments.

**Describe the solution you'd like**
The ability to specify additional docker run arguments, such as `--network`, `--memory`, `--privileged`, and potentially others.

**Comment by sdaschner** [comment]
**Update:** `--network` is obviously already implemented, should have researched better, sorry for that.

This leaves the question open for potential other arguments.

**Comment by chilanti** [comment]
Another one that comes to mind is `--sudo`. We now tell RHEL users to add their user id to the `docker` group because we can't force appsody to run `sudo docker` commands. This is also part of a bigger discussion on Appsody "config" settings.

**Comment by nkseto** [comment]
One option that should be considered is the ability to pass environment variables `--env` as part of the docker run command.

**Comment by mhdawson** [comment]
Adding to the comment from @nkseto I think it would also have to include adding the env variables so they are present by default in the dockerfile that is created by the run command.  @nkseto otherwise it would be up to the deployer of the container to specify the env variables when deploying.

**Comment by neeraj-laad** [comment]
We should look at the possibility to explore if we can pass all arguments that appsody does not understand over to docker. 

Alternatively, we might add --dockerargs and then provide a list of options to pass on
