### ISSUE TITLE
Add possibility to init home-grown stack

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#119]
**Describe the bug**
Right now it's possible to build and use a home-grown stack by changing the `stack` in `.appsody-config.yaml`. However, it's not easily possible to `init` a new project without doing additional steps, e.g. opening a PR.

It should be easily possible to test created stacks locally without publishing them to another repo.

**To Reproduce**
1. Build own stack, e.g. `sdaschner/java-microprofile`
2. Not possible to init project: something similar to `appsody init sdaschner/java-microprofile` required

**Expected behavior**
Having an easy way to try out built stacks locally without publishing
them or creating PRs.

**If applicable please specify:**
 - CLI version: `appsody 0.2.5`

**Additional context**
Output:

```
[Error] Could not find a stack with the name sdaschner/java-microprofile:latest. Run `appsody list` to see the available stacks or -h for help.
```

**Comment by neeraj-laad** [comment]
@appsody/cli Would like to get your thoughts on this.

**Comment by ebullient** [comment]
This should work now w/ new publish tools.. the stuff in the ci directory can be used to create a test repo file that can be added via `appsody repo add` .. so this may not be an issue anymore.

**Comment by neeraj-laad** [comment]
We create a local index now as part of our CI. The same scripts can be run locally by executing `/ci/build.sh ../` Under /ci/assets there are <repo>-index-test.yaml files. 

You can easily add these to appsody by running `appsody repo add <local-name> <file:// url of index>`

Now you should be able to test the stack completely.

We have also updated the create / modify stack docs with the steps needed.
