### ISSUE TITLE
Interactive TTY in run commands required

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#122]
**Describe the bug**
Some commands that are executed as `APPSODY_RUN` require an interactive
TTY, that is to be able to type in something in the running terminal,
that ends up in the running process. The `liberty:dev` plugin, for example, listens for specific input and right now fails with an error, since it can't open up the input reader.

**To Reproduce**
1. Use a command that requires an std input, e.g. `mvn liberty:dev`
2. Error, see below.

**Expected behavior**
That the running command received user input in the same way as if it runs locally.

This requires first of all to run the docker container with flag `-i` (`--interactive`). Right now, it only runs with `-t` (`--tty`).

Also, we probably need to enhance the Go code how the process is executed internally. I've tried to fix and submit a PR, but I'm not really familiar with Go and so far failed. I suspect some changes to be made in `utils.go`, method `execAndListenWithWorkDirReturnErr`.

**If applicable please specify:**
 - CLI version: `appsody 0.2.5`
 - Stack you are using: `sdaschner/java-microprofile:0.3.0` (custom, with `mvn [...] liberty:dev` command)

**Additional context**

This is the exception that the `maven-liberty-plugin` throws when trying to read from stdin.

```
[Container] Exception in thread "Thread-11" java.util.NoSuchElementException: No line found
[Container]     at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
[Container]     at net.wasdev.wlp.common.plugins.util.DevUtil$HotkeyReader.readInput(DevUtil.java:582)
[Container]     at net.wasdev.wlp.common.plugins.util.DevUtil$HotkeyReader.run(DevUtil.java:572)
[Container]     at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by neeraj-laad** [comment]
@appsody/cli Would like to get your thoughts on this.

**Comment by gcharters** [comment]
@appsody/cli @neeraj-laad I'd like the MicroProfile stack to move over to use `mvn liberty:dev` in the next month or so and so having this fixed will be important.

**Comment by kylegc** [comment]
I think this is a valid requirement for appsody. I'll investigate this and come back with a design and sizing.

**Comment by kylegc** [comment]
Related #292, We need to ensure we preserve/resume outputting colors (full TTY support)

**Comment by kylegc** [comment]
@sdaschner @gcharters Unfortunately this is not simple to support. I've done some investigation and believe it is possible, but it will require reworking our io piping for the cli and the controller.

Would you please help us understand the use case and impact of this? I understand you want to use `liberty:dev`, but for instance, what is the interactive piece for? Is it possible to make `liberty:dev` non-interactive or does that invalidate the use case?

**Comment by kylegc** [comment]
Note: the changes to the CLI have been merged, but TTY will not be supported until a new controller releases.
