### ISSUE TITLE
Incorporate env variables in the .travis.yml

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#128]
**Is your feature request related to a problem? Please describe.**

We should try to utilize the env variables as much as possible so in the .travis.yml we have...
`wget https://github.com/appsody/controller/releases/download/0.2.2/appsody-controller` 
and we could change it to...
`wget https://github.com/${GH_ORG}/controller/releases/download/0.2.2/appsody-controller`

I am also considering moving the install-controller to the Makefile so the change would be in the Makefile and not the .travis.yml

**Comment by chilanti** [comment]
In fact - I think we should also introduce a Travis env var for the controller version:
https://github.com/${GH_ORG}/controller/releases/download/${CONTROLLER_VERSION}/appsody-controller

**Comment by neeraj-laad** [comment]
Why not use TRAVIS built-in env vars: https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

`TRAVIS_REPO_SLUG` and `TRAVIS_TAG`could give you this information.

**Comment by kewegner** [comment]
This is fixed by #194
