### ISSUE TITLE
make clean package results in error due to GH_ORG and GOLANGCI_LINT_BINARY

### ISSUE THREAD

**Issue by maximilien** [appsody/appsody#130]
**Describe the bug**

Running `make clean package` results in errors due to unecessary GH_ORG environment variable and also GOLANGCI_LINT_BINARY not being set properly when GOPATH has many entries

**To Reproduce**

1. Get latest version of appsody code
2. run `make clean package`
3. First you get error for GOLANGCI_LINT_BINARY
4. Later you get issues when it tries to download controller unless GH_ORG is set

Assumes `GH_ORG` is not an environment variable and `GOPATH` has many entries in it, e.g., `/Users/maximilien/Desktop/github/appsody:/Users/maximilien/go` or `/Users/maximilien/go:/Users/maximilien/Desktop/github/appsody`

**Expected behavior**

Completed build.

**Actual behaviour**

Two errors:

1. due to GOLANGCI_LINT_BINARY

```bash
➜  appsody git:(master) ✗ make clean package
Makefile:47: *** target pattern contains no `%'.  Stop
```

2. due to GH_ORG

```bash
➜  appsody git:(master) ✗ make clean package
rm -rf /Users/maximilien/Desktop/github/appsody/src/github.com/appsody/appsody/build
rm -rf /Users/maximilien/Desktop/github/appsody/src/github.com/appsody/appsody/package
rm -f O_PATH/bin/golangci-lint
go clean
# make docs md file
mkdir my-project

...
# many many lines of output

./debian/control
--2019-07-30 01:18:03--  https://github.com//controller/releases/download/0.2.2/appsody-controller
Resolving github.com (github.com)... 192.30.253.112
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-30 01:18:04 ERROR 404: Not Found.
```

**Environment Details (please complete the following information):**

Mac OS X

**If applicable please specify:**

N/A 

**Screenshots**

N/A

**Additional context**

Golang setup

```bash
➜  appsody git:(master) ✗ echo $GOPATH
/Users/maximilien/go:/Users/maximilien/Desktop/github/appsody
➜  appsody git:(master) ✗ go version
go version go1.12.7 darwin/amd6
```

**Comment by chilanti** [comment]
@maximilien - I've commented on the PR which I associated with this issue. Please let us know what you think - but GH_ORG is not unnecessary.

**Comment by maximilien** [comment]
@chilanti yes. See the [two options](https://github.com/appsody/appsody/pull/131#issuecomment-516515139) suggested. Let me know your preference or if you can see a better and I will do it. Thx.

**Comment by henrynash** [comment]
So I hit the GH_ORG issue as well. Is the correct fix simply to add this to the documentation on how to build from source?
