### ISSUE TITLE
Windows release is a tar.gz not a tar file

### ISSUE THREAD

**Issue by No9** [appsody/appsody#132]
**Describe the bug**
The release for windows has the incorrect extension and the commandline tar compensates for this automatically but if the user is using a graphical tool it's not clear what is going on.

**To Reproduce**
1. Download the build for https://github.com/appsody/appsody/releases/download/0.2.7/appsody-0.2.8-windows.tar 
2. Right click on the file and extract it 
3. A file is created
4. As there is no extension on this file it's not clear if it's an exe or an unzipped tar file.

**Expected behavior**
The file should have the correct extension `appsody-0.2.8-windows.tar.gz`

**Actual behaviour**
While the instructions for install refer to the command line users will right click the file in windows if they don't have command line tools installed it's not part of their usual workflow. 

**Environment Details (please complete the following information):**
 - OS: Windows 7
 - No command line tools installed.

**Comment by neeraj-laad** [comment]
@No9 Thansk for raising this issue. 
We will investigate ad update the status here soon.

@appsody/installers team can you please take a look at this?

**Comment by kewegner** [comment]
The user is using Windows 7.  Changing the file name does not help with the issue.
