### ISSUE TITLE
appsody init fails with segv if default is not set in repository yaml

### ISSUE THREAD

**Issue by kewegner** [appsody/appsody#147]
Steps:
0. I did not update my repository yaml to have default.
1. I Use current newest appsody/appsody code per #142 
2. run the following

 appsody init java-spring-boot2

A paninc happens on line 97 of init.go because it doesn't no what repo it is.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x146cd77]

goroutine 1 [running]:
github.com/appsody/appsody/cmd.glob..func9(0x19a73c0, 0xc0000c13f0, 0x1, 0x1, 0x0, 0x0)
	/Users/sesadmin/go/src/github.com/appsody/appsody/cmd/init.go:97 +0x437
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).execute(0x19a73c0, 0xc0000c1390, 0x1, 0x1, 0x19a73c0, 0xc0000c1390)
	/Users/sesadmin/go/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19a6a40, 0x146833e, 0x19a6a40, 0xc000143f88)
	/Users/sesadmin/go/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sesadmin/go/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:800
github.com/appsody/appsody/cmd.Execute(0x16126d0, 0x5)
	/Users/sesadmin/go/src/github.com/appsody/appsody/cmd/root.go:153 +0x57
main.main()
	/Users/sesadmin/go/src/github.com/appsody/appsody/main.go:26 +0x39

**Comment by chilanti** [comment]
This was fixed by https://github.com/appsody/appsody/pull/150
