### ISSUE TITLE
Sorting alphabetically list command

### ISSUE THREAD

**Issue by mhamwala** [appsody/appsody#151]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have any sorting mechanism for the output we get when we run `appsody list` or `appsody repo list`

**Describe the solution you'd like**
Would like to to see the capability of the output of `appsody list` appearing alphabetically.

**Describe alternatives you've considered**
Additionally, we could have the default repo always appearing at the top and then sort the rest of the repos alphabetically

**Additional context**
The first column **repo** should be sorted alphabetically then the second column **name** should be sorted alphabetically

**Comment by barecode** [comment]
+1 to addressing this. Its rather annoying that the order of my list changes on each execution. Its a minor annoyance but those do add up to negative impact the user experience.
