### ISSUE TITLE
Truncate appsody list command

### ISSUE THREAD

**Issue by mhamwala** [appsody/appsody#154]
**Is your feature request related to a problem? Please describe.**
The output of the `appsody list` command has gotten bigger as we have added in the templates and repo column. It's getting a bit tricky to fit the output on a screen.

**Describe the solution you'd like**
We should truncate the characters at the end of the description with 3 dots if the number of characters exceeds 80 chars.
example:
```
REPO       NAME             	VERSION	DESCRIPTION
appsodyhub nodejs-express   	0.2.2  	Express web framework for No...
appsodyhub swift            	0.1.0  	Swift runtime
appsodyhub java-microprofile	0.2.3  	Microprofile using AdoptOpen...
appsodyhub java-spring-boot2	0.3.2  	Spring Boot using IBM Java S...
appsodyhub nodejs           	0.2.2  	Node.js Runtime
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kewegner** [comment]
Fixed in #165
