### ISSUE TITLE
CLI reference doc generation does not include title front matter

### ISSUE THREAD

**Issue by tomleah** [appsody/appsody#176]
**Describe the bug**
The website now requires all documentation to contain `title` in the front matter. This is so that the doc is visible when using the search bar (https://github.com/appsody/website/pull/158).

When the CLI Reference is generated by a CLI release it does not include the required front matter so the pull request into the website tries to remove it.

**To Reproduce**
1. Generate CLI Reference documentation

**Expected behavior**
Front matter should look like the following 
```
---
title: CLI Reference
path: /docs/using-appsody/cli-commands
---
```

**Actual behaviour**
What is the actual behaviour.
```
---
path: /docs/using-appsody/cli-commands
---
```
and `title` is therefore removed from upstream

**Comment by kewegner** [comment]
This should be fixed in #175
