### ISSUE TITLE
Improve cli development process documentation

### ISSUE THREAD

**Issue by kewegner** [appsody/appsody#177]
We should highlight the following for contributing new code to appsody:
- Enhance the documentation for the various tags in the makefile
- Enhance the documentation for .travis.yaml
- New developers should use make test locally to test their code prior to doing PRs
-New developers should use make lint locally to lint their code prior to doing PRs
- Clarify how to set up the binaries (appsody and appsody-controller) when developing new function for appsody locally

**Comment by henrynash** [comment]
I strongly agree with this (having just had to go through working out nearly all of the above from first principles for this first time!). If this is already being worked on, then great, otherwise, I'd be happy to take a crack updating the documentation, if that would help.

**Comment by chilanti** [comment]
@henrynash - are you still available to work on this? If you are - feel free to assign this to yourself. Thanks.

**Comment by henrynash** [comment]
HI, yes, I'll pick this one up...
