### ISSUE TITLE
Update Release.md to describe how to update .travis.yaml when the controller verison changes prior to doing a new Release

### ISSUE THREAD

**Issue by kewegner** [appsody/appsody#178]
It would be helpful for new contributors if the Release.md file described the neccessary updates for the URL in .travis.yaml which is used by WGET to get the controller binary.

Specifically the release version of the controller to be used.  This will be moved to the Makefile, so this needs to be described.

**Comment by chilanti** [comment]
This was fixed in https://github.com/appsody/appsody/pull/201. Closing.
