### ISSUE TITLE
Update documentation to include APPSODY_PROJECT_DIR

### ISSUE THREAD

**Issue by kewegner** [appsody/appsody#195]
Per @neeraj-laad 

@seabaylea @kewegner We should update the environment variable docs https://github.com/appsody/website/blob/master/content/docs/stacks/environment-variables.md along with this change

This issue is opened to track this work.

**Comment by Kamran64** [comment]
I believe https://github.com/appsody/website/pull/182 put in a fix for this one. Closing now :)
