### ISSUE TITLE
appsody delete does not work if not using the default namespace

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#221]
**Describe the bug**
If a non-default namespace is used for a deploy there does not appear to be a way to delete it as there is no `--namespace` parm for `appsody delete`

**To Reproduce**
1. start docker desktop and its k8s
2. create a non-default namespace
`kubectl create ns test`
3. `mkdir nodejs`
4. `cd nodejs`
5. `appsody init nodejs`
6. `appsody deploy --namespace test`
7. `appsody delete`

**Expected behavior**
expected the delete to find the non-default namespace or expected a `--namespace` parm for `appsody delete`

**Actual behaviour**
```
supra:nodejs2 tnixa$ appsody delete
Deleting deployment using deployment manifest app-deploy.yaml
Attempting to delete resource from Kubernetes...
Running command: kubectl[delete -f app-deploy.yaml --namespace default]
[Error] Error from server (NotFound): error when deleting "app-deploy.yaml": appsodyapplications.appsody.dev "nodejs2" not found
[Error] kubectl delete failed: exit status 1
[Error] exit status 1
```

**Environment Details (please complete the following information):**
 - OS: mac

**If applicable please specify:**
 - CLI version: 0.3.0 plus fixes
 - Stack you are using: nodejs

**Comment by kewegner** [comment]
I think this works now with appsody deploy delete --namespace, I just tried it.
