### ISSUE TITLE
Update repo using old V1 index to use the V2 index

### ISSUE THREAD

**Issue by tomleah** [appsody/appsody#223]
V1 index that is in master is deprecated and is not reliably updated. Now we automatically update the V2 index on release we should move CLI users to the V2 index.

V1 index: https://raw.githubusercontent.com/appsody/stacks/master/index.yaml
V2 index: https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml

We should check to see if the V1 index is being used and if so swap it out to the V2 index.

**Comment by mhamwala** [comment]
My suggestion would be to note this down as a known issue somewhere (FAQ maybe?) and manually deal with breakages. The main reason I'm against adding code to handle this is:

- This check would be redundant after the first check.

- We changed the index URL so the CLI currently looks for the **latest** index.yaml so even when V3 is released I don't think we would need this check

- At some point, we might want to consider tying index versions to a particular release of the CLI, this change would block that if users are automatically upgraded to use the latest index version.

thoughts @appsody/cli?

**Comment by cmoulliard** [comment]
@gastaldi Should be good that `f8 launcher catalog` adopt this index v2 spec to unify our efforts and been able in the future to propose perhaps different repos but adhering to the same spec that `appsody repo list` could use and next `appsody init` to scaffold a project. WDYT ?

**Comment by gastaldi** [comment]
@cmoulliard yes, that sounds like a good idea
