### ISSUE TITLE
appsody deploy fails when there is an underscore in the project name

### ISSUE THREAD

**Issue by tomleah** [appsody/appsody#224]
**Describe the bug**

**To Reproduce**
1. Make sure you have Knative configured in you kube cluster
1. Make project directory, including an underscore: `mkdir my_project`
1. Initialize an appsody stack: `appsody init nodejs-express` 
1. Run `appsody deploy`
1. See error

**Expected behavior**
```|Deploying your project to Kubernetes...
Running command: kubectl[apply -f /Users/thomasleah/tmp/my_project/appsody-service-468376984.yaml]
Deployment succeeded.
Running command: kubectl[get rt my-project -o jsonpath="{.status.url}"]
Your deployed service is available at the following URL: "http://my-project.default.<external-url>.nip.io"
```

**Actual behaviour**
```
Deploying your project to Kubernetes...
Running command: kubectl[apply -f /Users/thomasleah/tmp/my_project/appsody-service-468376984.yaml]
[Error] kubectl apply failed: exit status 1 
[Error] Failed to deploy to your Kubernetes cluster: exit status 1
```

**Environment Details (please complete the following information):**
 - OS: macOS

**If applicable please specify:**
 - CLI version: 0.3.0
 - Stack you are using: nodejs-express

**Additional context**
You can get a better error by running the deploy command manually after it has failed using `appsody deploy`.

`kubectl apply -f $(pwd)/appsody-service-<ID>.yaml`
```
Error from server (InternalError): error when creating "/Users/thomasleah/tmp/my_project/appsody-service-468376984.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: not a DNS 1035 label: [a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]: metadata.name
```
**Edit:** as of appsody 0.4.0 the error is now
```
The AppsodyApplication "my_project" is invalid: metadata.name: Invalid value: "my_project": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
due to the deploy using the operator and not a Knative service.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by kewegner** [comment]
This also happens on the operator path as well.

**Comment by tomleah** [comment]
Thanks @chilanti, I believe this is where @Bazif-Khan implemented the fix. Good to know we were on the right path
