### ISSUE TITLE
Add support for local stack building to appsody CLI

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#262]
When development stacks, the local build process (i.e. using the ci scripts), while reasonable, requires the developer to understand a bit too much...and is somewhat cumbersome. It might be better if the appsody CLI itself supported this process directly, e.g.:

appsody stack cmd [stack-name] [local-repo-name]

cmd - can be build, lint, test or package

stack-name, if not specified would default to the current directory (e.g. experimental/my-stack). 

local-repo-name, if not specified, would default to "local-test"

We might also add a flag to 'appsody init' to use local repos (i.e. the equivalent of setting 'export APPSODY_PULL_POLICY=IFNOTPRESENT')

**Comment by kylegc** [comment]
Hi Henry, thanks for creating this issue! We actually already have an Epic #45 for this, so I'm closing this as a duplicate. However I've copied your ideas above into the epic.
