### ISSUE TITLE
Add CLI flag to target knative deployment

### ISSUE THREAD

**Issue by ykoyfman** [appsody/appsody#263]
Currently, `appsody deploy` deploys via the Appsody operator if it's supported.  It may be good to have a flag to force knative deployement.

**Comment by neeraj-laad** [comment]
There is a flag that can be set in `app-deploy.yaml` that will use the Appsody operator to do create a knative service. So, `appsody deploy` always uses appsody operator but the developer can modify the deployment config file to specify if they need a knative or kubernetes based deployment.

createKnativeService: A boolean to toggle the creation of Knative resources and usage of Knative serving.

I believe this should suffice for the use case as users a re likely going to modify the config. 

@ykoyfman please confirm if you still see the need for a knative deployment as a CLI flag.

**Comment by ykoyfman** [comment]
@neeraj-laad Thanks! Closing issue.
