### ISSUE TITLE
Create stacks linter to validate a stack

### ISSUE THREAD

**Issue by Kamran64** [appsody/appsody#269]
https://github.com/appsody/stacks/pull/166 added a basic Linter to validate the directory structure of each stack. We could take this one step further by scanning through files to ensure formatting is consistent. 

**Requirements**
- ```appsody stack lint``` should be run from the base of the stack
- Path to stack can be specified as an alternative

**We need to:**

Add:
 - [x] An ```appsody``` command: ```appsody stack lint```

Validate:
 - [x] Folder structure
 - [x] ```stack.yaml```
 - [x] ```Dockerfile-stack```
 - [ ] ```app-deploy.yaml```

**Extra**
- Add rules to the comment below

**Comment by neeraj-laad** [comment]
All is in place except for validating app-deploy.yaml. We do not intend to validate this file as part of stack linting as we are looking to remove this file from the stacks and have the cli generate this.
