### ISSUE TITLE
Provide Contribution Guide

### ISSUE THREAD

**Issue by erpenbach** [appsody/appsody#27]
Need to provide a contribution guilde with the appropriate license information such as https://github.com/OpenLiberty/open-liberty/blob/integration/CONTRIBUTING.md

**Comment by neeraj-laad** [comment]
@erpenbach Thanks for raising this issue.

The README.md files in each of our repos link too the project contribution guidelines - https://github.com/appsody/docs/blob/master/CONTRIBUTING.md

Is there anything specific that you could not find in this guide?

**Comment by erpenbach** [comment]
I now see the Contributing information is on the Overview page of the documentation.  Closing out.
