### ISSUE TITLE
Document that APPSODY_RUN_ON_CHANGE is not used if application doesn't keep running

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#272]
If APPSODY_RUN_KILL is set to false, then when a change is detected, APPSODY_RUN is executed, rather than APPSODY_RUN_ON_CHANGE. The same is true for TEST/DEBUG. If APPSODY_RUN_KILL is set to true, then it works as advertised.

Although somewhat a corner case (since I would think usually RUN_KILL is true), we should either make this consistent or document why it is not.

**Comment by kewegner** [comment]
Does the process started by APPSODY_RUN stay alive?  There is code in the controller to check if it is, and if it is not, it will run APPSODY_RUN rather than APPSODY_RUN_ON_CHANGE. (In the case that APPSODY_RUN_KILL is false). Which stack did this occur in?

**Comment by henrynash** [comment]
So I found this as I was developing https://github.com/appsody/stacks/pull/311. Since this is a sample stack, it just fires a shell script as the APPSODY_RUN, so it doesn't stay running. So it sounds like it operating as coded :-), and sounds like my description is wrong. I did wonder if that was the case. I agree that there seems much less need to have an APPSODY_RUN_ON_CHANGE if the original app isn't still running - although we should, in that case, clarify how this works in the docs. Alternatively, it *might* be cleaner to always use APPSODY_RUN_ON_CHANGE, unless there is a good reason not to?

**Comment by kewegner** [comment]
I agree we are way behind in the docs.  Yes if the script just exits, that's why you are seeing what you are seeing.  If the APPSODY_RUN command dies for a bad reason, such as a java file that won't compile, we will run APPSODY_RUN until it is fixed, then we will use APPSODY_RUN_ON_CHANGE thereafter.

Unfortunately some stacks have a distinct differences between APPSODY_RUN and APPSODY_RUN_ON_CHANGE, so I don't think your latter suggestion will work at present.
Also the APPSODY_RUN calls on certain stacks do not tolerate failures very well, and the APPSODY_<r/d/t>_ON_CHANGE actions they specify aren't enough to make the runtime for the stack whole.

**Comment by henrynash** [comment]
..actually what I was suggesting was to call APPSODY_RUN_ON_CHANGE even if the application had exited. However, I guess that might cause problems if we can't tell an intended exit vs an un-intended one. At least for now, I guess we just amend the docs - I'd be happy to do that.

**Comment by kewegner** [comment]
@henrynash, we should update the docs.  Might I suggest we change the title of this issue to something like.  "Document Controller behavior for APPSODY_<>_KILL".

The issue could also be moved to the appsody/controller or appsody/website repo? Depending on which document is used.  The best current possibility might be environment-variables.md in the website content/docs.

I think there is a larger need for more controller documentation -- targeted though that audience might be.  I suggested earlier this AM that in a future sprint there is a need for a controller issues Epic in general, this could also fold into that.


I agree with your analysis, right now we can't tell the reason why a particular stack exits.

**Comment by henrynash** [comment]
I will close this here and re-open in website.
