### ISSUE TITLE
Appsody deploy with Knative option fails to prefix the image name

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#281]
**Describe the bug**
When attempting `appsody deploy` with the Knative option for the Appsody operator, the CLI fails to prefix the image name with `dev.local` (which is the conventional prefix chosen to enable Knative to skip the retrieval of the digest).

**To Reproduce**
1. On an Appsody project, run `appsody deploy --generate-only`
2. Edit the `config/app-deploy.yaml` to add the Knative deployment option.
3. Run `appsody deploy`.
4. Knative deployment fails with some authentication error.

**Expected behavior**
The image should be named `dev.local/<projectname>` in this case. Knative (if properly configured) would then skip the step that attempts the retrieval of the image digest and just let Docker-for-desktop download the image.

**Actual behaviour**
Knative fails to fully deploy the service

**Environment Details (please complete the following information):**
all

**If applicable please specify:**
 - CLI version: 0.4.2
 - Stack you are using: Any

**Comment by chilanti** [comment]
This is related to https://github.com/appsody/appsody-operator/issues/87

**Comment by neeraj-laad** [comment]
this has been fixed by adding new option to deploy as knative service.
