### ISSUE TITLE
Add --project-name option to init, add the name to .appsody-config.yaml, and validate it against k8s rules

### ISSUE THREAD

**Issue by mtamboli** [appsody/appsody#287]
**Describe the bug**
If the name of the appsody directory is not what Kubernetes service likes, pod will not come up during deployment. Directory name for the appsody project is used for the service.

AppsodyApplication or KnativeService create ServiceSpec objects that must conform to RFC-1123 naming
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/
appsody init should check that the name conforms
https://github.com/kubernetes/kubernetes/blob/v1.15.3/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go

**To Reproduce**
1. mkdir jmp/1-2
2. cd jmp/1-2
3. appsody init Kabanero/ava-microprofile
4. appsody deploy --generate-only
5. app-deploy.xml file is created and it has the directory name "1-2" in that file.
Then the application was used with Kabanero pipeline, application pod did not start.
because of the deployment failure:
```
 Message:           Service "1-2" is invalid: metadata.name: Invalid value: "1-2": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

**Expected behavior**
I would expect error to be displayed during `appsody init` if directory name is going to be a problem. If not during appsody init, then definitely during `deploy --generate-only'. Need to catch the error earlier.

**Environment Details (please complete the following information):**
OpenShift 3.1.1
Kabanero release 0.1.2

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by chilanti** [comment]
This needs discussion - @neeraj-laad and @kyle. 
I think we have been sort of skirting the problem of special characters in Appsody paths for a while (in some cases we turn underscores into dashes, etc.) - but this is a bigger issue, with the potential for a number of consequences (see also #31).

**Comment by skoh7645** [comment]
@chilanti In case 2 we would still need to check the project dir against the regex?

**Comment by skoh7645** [comment]
@mtamboli we have to make sure the project name starts with an alphabetic char an ends on an alphanumeric char.
Perhaps we should only append/prepend if project name doesn't start/end on a valid char?

**Comment by chilanti** [comment]
> @chilanti In case 2 we would still need to check the project dir against the regex and convert it if necessary?

@skoh7645 - yes.

**Comment by chilanti** [comment]
> @mtamboli we have to make sure the project name starts with an alphabetic char an ends on an alphanumeric char.
> Perhaps we should only append/prepend if project name doesn't start/end on a valid char?

Right - @mtamboli - it's K8S that's really fussy with names. 
After some discussions, we suggest:
1) Pre-pend and append only if necessary
2) Append `-app` instead of `-project`
3) Please avoid double `-` as in `appsody-my-dirname--app` (which might occur if the dirname ends in a special character, after conversion)

**Comment by chilanti** [comment]
More details on the design: 
1) Create a new flag in `init` called `--project-name`. If not set, default to using the dir name
2) `appsody init` saves the project name (either set or generated) in `.appsody-config.yaml` as  key/value `project-name: <project name>`
3) `getProjectName` just gets that value.

**Comment by ebullient** [comment]
"If not set, default to using the dir name" --> "If not set, default to using the _sanitized_ dir name"

Avoid prefix-suffix games.
