### ISSUE TITLE
Linter: Validate app-deploy.yaml

### ISSUE THREAD

**Issue by Bazif-Khan** [appsody/appsody#291]
**Is your feature request related to a problem? Please describe.**
Currently, the stacks linter will only verify that an app-deploy.yaml exists, but won't actually validate the contents of the file. As a result, the lint test will pass even if the file is empty/contains the wrong fields.

**Describe the solution you'd like**
For now we could have a mechanism that scans through the file and ensures:
- apiVersion
- kind
- metadata
- spec

are all present and have a value.

**Comment by neeraj-laad** [comment]
Closing this issue as we are considering removing this file from the stack completely.
