### ISSUE TITLE
appsody run --docker-options prohibits -e

### ISSUE THREAD

**Issue by GregDritschler** [appsody/appsody#301]
**Describe the bug**
It is not possible to pass environment variables to the container.

>appsody run --docker-options "-e spring_profiles_active=dev"
Running development environment...
Running command: docker[pull appsody/java-spring-boot2:0.3]
testing docker options [-e spring_profiles_active=dev]
[Error] -e is not allowed in --docker-options

**To Reproduce**
appsody run --docker-options "-e spring_profiles_active=dev"

**Expected behavior**
Environment variable is passed to the container.

**Actual behaviour**
appsody disallows passing any environment variable to the container.

**Environment Details (please complete the following information):**
 - OS: Windows 10

**If applicable please specify:**
 - CLI version: 0.4.2
 - Stack you are using: java-spring-boot2

**Screenshots**

**Additional context**
1) It is very common to pass dynamic configuration into containers via environment variables.  For example, in Kubernetes the values of secrets can be passed as environment variables.  It is likely that developers will want to be able to imitate this behavior when using appsody run.

2) Profiles are a very popular Spring feature but there's no way to select one dynamically due to this restriction.

**Comment by gireeshpunathil** [comment]
Agree that disallowing to set running environment will handicap developers heavily. IMO either of:
 - print a warning message if `-e` option is set irrespective of `APPSODY..` env is touched or not
 - print a warning message if `-e` option is set and `APPSODY..` env is touched

**Comment by chilanti** [comment]
Fixed by PR #320
