### ISSUE TITLE
Appsody deploy: add ability to select Knative deployment option

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#303]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to obtain a Knative service deployment for an appsody application requires manually editing the generated `app-deploy.yaml`, and then submitting `appsody deploy` again. 

**Describe the solution you'd like**
`appsody deploy` should support a flag to direct the generation of an `app-deploy.yaml` file that would produce a Knative deployment.
Also, for local Knative deployment, the image should be named `dev.local/<project-name>`, as documented, to let Knative skip the digest retrieval for the image (unless the user explicitly tags the image with the `-t` flag).

**Comment by sympatheticmoose** [comment]
My only concern is _generally_ we are adding a number of new flags/options to the CLI. All of which make sense in isolation - but we are introducing complexity. I would like to have a review of the CLI experience with a UX designer ASAP.

**Comment by chilanti** [comment]
Yes - there has been a proliferation of flags. Frankly, not unique to appsody (look at `kubectl` or `docker`). I'd love to hear what a designer has to say.
