### ISSUE TITLE
Appsody list: provide better debugging messages on HTTP failures

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#304]
**Describe the bug**
Right now, the CLI doesn't produce any meaningful insight as to why an HTTP request against the appsody repos fails.

**To Reproduce**
1. Modify the repository.yaml to include URLs that can't be reached or that error out for different reasons.
2. run `appsody list -v`
3. No HTTP code is provided that clarifies the specific error

**Expected behavior**
HTTP return codes should be printed out in Debug mode (at a minimum)

**Actual behaviour**
We print out the response.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
@kewegner is this complete and can be closed?

**Comment by kewegner** [comment]
I think we can close this, because we do print out code and message in the error, the problem is that there was no response object.  So for instance we see like a 404 error, and status not found.  
But if there is no response, there is no way to get a status code or status.
