### ISSUE TITLE
appsody-setup.bat only works if appsody isn't already installed.

### ISSUE THREAD

**Issue by BarDweller** [appsody/appsody#321]
**Describe the bug**
If you already have a version of appsody installed, and you try to install a new version of appsody from a different directory, appsody-setup.bat will append the new location to the path. This places it in the search order AFTER the existing version, so you end up with the previous version still active on your path. This isn't the behavior most people expect from setup, where after running setup the new thing you just installed would be thing you end up with being active. 

**To Reproduce**
1. download two different versions of appsody
2. extract each tar.gz to a folder with the same name as the archive (eg appsody-0.4.x-windows)
3. install one version via appsody-setup.bat
4. check which version of appsody is active using appsody version (or check your path content)
5. install the other version of appsody via appsody-setup.bat
6. check again the appsody version active, and find it's the version installed in step 3, not the one from step 5. 

**Expected behavior**
Either of:
Latest install of appsody becomes the active version.
or:
Appsody notices appsody is already on the path during setup, and asks if you would like to replace that version with this version in the path. 

**Actual behaviour**
What is the actual behaviour.

Appsody appends the latest installed version to the end of the path, leaving any earlier installed versions ahead of it with no warnings.

**Environment Details (please complete the following information):**
 - OS: Windows 10

**If applicable please specify:**
 - CLI version: more than one =)

**Comment by chilanti** [comment]
Known issue - this is why we documented the fact that you need to manually remove the entry from the Windows env vars if you really really want to clean up Appsody and re-install it:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7307387/64902737-5e67fd80-d672-11e9-8983-b7a7c9665e26.png">

We'll look into automating this in one of the upcoming releases.
