### ISSUE TITLE
`--docker-options` needs hardening

### ISSUE THREAD

**Issue by gireeshpunathil** [appsody/appsody#346]
**Describe the bug**
The command line parser needs to make stricter rules allow only valid set of inputs

**To Reproduce**

```
#appsody run --docker-options=-t
Running development environment...
Running command: docker pull appsody/nodejs-express:0.2
testing docker options [-t]
[Error] -t is not allowed in --docker-options
```
 - good

```
#appsody run --docker-options=-it
Running development environment...
Running command: docker pull appsody/nodejs-express:0.2
testing docker options [-it]
Running docker command: docker run --rm -p 3000:3000 -p 9229:9229 --name foo-dev -v /Users/gireeshpunathil/Desktop/t/foo/:/project/user-app -v foo-deps:/project/user-app/node_modules -v /Users/gireeshpunathil/.appsody/appsody-controller:/appsody/appsody-controller -it -t --entrypoint /appsody/appsody-controller appsody/nodejs-express:0.2 --mode=run
[Container] the input device is not a TTY
[Error] Error waiting in 'appsody run' exit status 1
```
 - not so good

```
#appsody run --docker-options="ubuntu bash -c whoami"
Running development environment...
Running command: docker pull appsody/nodejs-express:0.2
testing docker options [ubuntu bash -c whoami]
Running docker command: docker run --rm -p 3000:3000 -p 9229:9229 --name foo-dev -v /Users/gireeshpunathil/Desktop/t/foo/:/project/user-app -v foo-deps:/project/user-app/node_modules -v /Users/gireeshpunathil/.appsody/appsody-controller:/appsody/appsody-controller ubuntu bash -c whoami -t --entrypoint /appsody/appsody-controller appsody/nodejs-express:0.2 --mode=run
[Container] Unable to find image 'ubuntu:latest' locally
[Container] latest: Pulling from library/ubuntu
[Container] 5667fdb72017: Pulling fs layer
...
[Container] Digest: sha256:b88f8848e9a1a4e4558ba7cfc4acc5879e1d0e7ac06401409062ad2627e6fb58
[Container] Status: Downloaded newer image for ubuntu:latest
[Container] root
#
```
 - it pulls the ubuntu image, not good

```
#appsody run --docker-options=--help
Running development environment...
Running command: docker pull appsody/nodejs-express:0.2
testing docker options [--help]
Running docker command: docker run --rm -p 3000:3000 -p 9229:9229 --name foo-dev -v /Users/gireeshpunathil/Desktop/t/foo/:/project/user-app -v foo-deps:/project/user-app/node_modules -v /Users/gireeshpunathil/.appsody/appsody-controller:/appsody/appsody-controller --help -t --entrypoint /appsody/appsody-controller appsody/nodejs-express:0.2 --mode=run
[Container] 
[Container] Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
[Container] 
[Container] Run a command in a new container
[Container] 
[Container] Options:
[Container]       --add-host list                  Add a custom host-to-IP mapping
[Container]                                        (host:ip)
[Container]   -a, --attach list                    Attach to STDIN, STDOUT or STDERR
[Container]       --blkio-weight uint16            Block IO (relative weight),
[Container]                                        between 10 and 1000, or 0 to
...
```
 - the help opton is percolated to docker, I guess not good.

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

A well defined outcome for invalid inputs

**Environment Details (please complete the following information):**
any
**If applicable please specify:**
any
**Screenshots**
na

**Additional context**
na

**Comment by gireeshpunathil** [comment]
thinking further on this, I guess:

 - it is not easy (nor meaningful) to validate every docker options that is passed
 - even if we do, docker flags can change upstream and maintaining it locally can be hard
 - blacklisting anything that does not start with a `-` looks to be a reasonable approach
 - in addition, black-list `--help` too: as `appsody` is not the best way to get `docker run --help`

let me know what do you think; I am coming up with a regexp to that effect, but open to suggestions!

**Comment by kylegc** [comment]
Hi Gireesh, thanks for taking a look at this. As you and Kim pointed out here and in PR #355, it is difficult to validate the docker options. Blacklisting everything that doesn't start with a `-` won't work because of option parameters. And we don't want to recreate docker and get into a maintenance nightmare (this is why we stopped adding docker options directly to the appsody command).

All considered, I don't think the consequences of a user entering invalid docker arguments are bad enough to justify the work and maintenance required to validate the arguments. Obviously if the user enters bad arguments appsody will not work, so they will have to fix them. No harm done really.

Thus, I'm going to close this issue. If others feel strongly another way we can reopen and reconsider it.

**Comment by gireeshpunathil** [comment]
@kylegc - I understand, and agree with your assertions. thanks! I will go just with blacklisting `--help` (makes sense to do, easy to do, good to do as its o/p is truncated atm)
