### ISSUE TITLE
Need way to not-truncate output from appsody repo list

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#350]
**Describe the bug**

When doing `appsody repo list`, the output is truncated if the URL happens to be very long:

```
appsody repo list

NAME       	URL                                                                                                                     
*appsodyhub	https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml                                         
kabanero   	http://kabanero-collections.csantana-ocp3-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud/ka...
```

This breaks Codewind, which needs the name of the `xxx-index.yaml` in order to locate the corresponding `xxx-index.json` to parse.

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by kylegc** [comment]
Thanks, we'll try to remove the truncation.

**Comment by makandre** [comment]
When will this fix go into a release?

**Comment by kylegc** [comment]
This will be part of the next release. We release approximately every two weeks making the next release later this week.
