### ISSUE TITLE
It would be better if --generate-only took account of any image name specified by -t

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#364]
Many deploys will be of the form:

`appsody deploy -t some-registry.io/xyz/app`

If I also want to add a PullSecret ahead of the actual deploy, I'll want to do a generate only, and then add it. So I assumed I would do:

`appsody deploy -t some-registry.io/xyz/app --generate-only`

...but this does not put some-registry.io/xyz/app into the app-deploy.yaml (it remains the name of the appsody directory). While I appreciate this is then overwritten again on the actual deploy, this seems like a confusion we don't need to create.

Hence, `--generate-only` should insert any target image specified by the -t option, into the app-deploy.yaml. This would then not need to specified on the actual deploy line again.

**Comment by kewegner** [comment]
Fixed by #370
