### ISSUE TITLE
Source code changes not detected by container during `appsody run` (Windows only)

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#366]
**Describe the bug**
This issue is specific to Windows, and very likely a side-effect of https://github.com/docker/for-win/issues/56

**To Reproduce**
1. Create a new appsody application with `appsody init java-microprofile`
2. Issue `appsody run`
3. Modify and save the StarterApplication.java file for the application. The change in itself is not important, for instance, add a comment.

**Expected behavior**
You should see the appsody console immediately notice the change and start recompiling the application:
```
[Container] [INFO] Scanning for projects...
[Container] [INFO] 
[Container] [INFO] ---------< dev.appsody.starter.java-microprofile:starter-app >----------
[Container] [INFO] Building starter-app 1.0-SNAPSHOT
[Container] [INFO] --------------------------------[ war ]---------------------------------
```

**Actual behaviour**
On Windows, nothing happens on the container.

**Environment Details (please complete the following information):**
 - OS: Windows 10 Enterprise (though the problem is not specific to the Enterprise edition)
 - Browser: N/A
 - Version N/A

**If applicable please specify:**
 - CLI version: appsody 0.4.5
 - Stack you are using: java-microprofile

**Screenshots**

**Additional context**
If you log into the container, with `docker exec -it container_name /bin/bash` and the use `touch /project/user-app/src/main/java/dev/appsody/starter/StarterApplication.java`, you can see the container detecting the change and recompiling the application.

Changes to HTML files are reflected when the user refreshes the local browser because the user drives the change with a "Refresh" operation.

**Comment by nastacio** [comment]
At the core, this is caused by a shortcoming in the way Windows exposes filesystems to Docker, but it mars the Appsody experience on Windows to a point where people may question the value of developing and using collections.

Maybe there is room for using something like https://github.com/appsody/watcher on the mounted filesystems for user applications and then triggering the appropriate filesystem notifications from within the container.a

**Comment by chilanti** [comment]
@nastacio - this is surprising because we did test these scenarios on Win 10. We'll be re-testing, but at this point I suspect that there's a discrepancy in the Docker level that we've been using all along. What's yours?

**Comment by tnixa** [comment]
I am unable to recreate this problem on my Win10 box with docker desktop version 2.1.0.3 (38240)

**Comment by kewegner** [comment]
It may or not be important, but when you changed the file, what program (editor) did you use if any in Windows 10?

**Comment by nastacio** [comment]
I see the problem with my scenario. This was not the java-microprofile stack, but rather a modified version of it using Liberty in development mode. I did not have my Windows laptop with me in the afternoon when I wrote the defect, so I wrote the recreation steps based on memory.

I just got back to it and verified that java-microprofile works.

My apologies for the false alarm.

**Comment by seabaylea** [comment]
Note that we will have this problem if we want to switch to using Liberty's new dev mode rather than appsody's watcher for Java files.

There is a tactical solution that can be provided whilst waiting for the real fix for this to appear in Docker on Windows, and that's the run a watcher on the windows file system that notifies the container of the file changes. 

We trialed that at a workshop this week using a Go binary - if needed we could potentially build that into the appsody CLI as part of a tactical solution. @gcharters has the details.
