### ISSUE TITLE
Better document --docker-options flag, specifically what is not allowed

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#367]
See slack thread https://ibm-cloudplatform.slack.com/archives/GJJL89Z0E/p1569412619006700

**Comment by neeraj-laad** [comment]
@kewegner are you working on this?

**Comment by kewegner** [comment]
Yes

**Comment by neeraj-laad** [comment]
@kewegner do you want to add an update on this issue?

**Comment by kewegner** [comment]
@neeraj-laad I will get this in this week.  It got delayed by other stuff.
