### ISSUE TITLE
Implement the `appsody stack create` command

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#368]
The first pass of an `appsody stack create` command will create a new stack as a copy of an existing stack.

FUTURE: in the future, we may add an `--extends` option to create a new stack that inherits from an existing stack. This is out of scope right now.

Usage: `appsody stack create <name> --copy <stack>`
* --copy is optional, without it, default to "samples/sample-stack"
Example: `appsody stack create java-liberty --copy incubator/java-microprofile`

## Steps of the command --copy
1. Create a directory called <name> under the current directory (maybe add a --target option for the parent dir)
2. Download "--copy stack" from git (using http github rest api)
3. (If not already done by step 2) Copy stack contents to directory created in step 1

**Comment by neeraj-laad** [comment]
@appsody/cli just wondering if we will always create a stack based on appsody/stacks repo. OR should we allow users to specify their own git repo. I'm thinking users or enterprises who might be maintaining a fork of appsody/stacks.

**Comment by kylegc** [comment]
Good question Neeraj. I think for now assuming the appsody/stacks repo is okay, but I agree the enterprise scenario needs to be addressed. 

We could have an option on the command to specify the git repo, but I'm thinking we can do better. Eventually we should be able to link the stacks back to their github repo source via either the stack image labels or the repo index. We could use that information to then download the source for the `stack create` command.
