### ISSUE TITLE
Support passing environment variables via a file

### ISSUE THREAD

**Issue by jaricsng** [appsody/appsody#373]
## Summary

In existing nodejs application, it uses dotenv to get environment variable.

i ran the following command 

```
$ appsody version
appsody 0.4.5
```

```
$ appsody init nodejs none
```

after building to a docker image, i can run as shown below

***example***
```
$ docker run -e CONTAINER_PORT='3000' -e TARGET_URL='https://httpbin.org/' -e TARGET_URI='delay/1' -d -p 5000:3000 js-nodeapp:1.0
```

how can I do similar with **```appsody run```**, i noted ability the provide **-p** for ports mapping but -e is not recognized.

**Comment by seabaylea** [comment]
You can use `--docker-options "<options>"` to pass additional options to the underlying `docker run` command.

We're also considering adding a specific file for setting environment variables (eg, `appsody.env`) which, if present, will be passed into docker run using `--env-file`.

**Comment by kylegc** [comment]
As Chris said, today you can use the command line `appsody run --docker-options "-e key=value"`

I'll repurpose this issue to consider supporting a .env file.

**Comment by kylegc** [comment]
It was pointed out to my that you can also do `appsody run --docker-options "--env-file .env"` to read environment variables from a file.

**Comment by navidsh** [comment]
> We're also considering adding a specific file for setting environment variables (eg, `appsody.env`) which, if present, will be passed into docker run using `--env-file`.

@seabaylea Is this file (i.e.`appsody.env`) going to be passed to `spec.env` in `AppsodyApplication` during `appsody deploy`?

**Comment by jaricsng** [comment]
hi

the recommended ```appsody run --docker-options "-e key=value"``` works where variable are passed to application but I noted another **issue**.

my original application when run with docker cmd above, allows user to defined the container port (3000) of the nodejs, and I would be able to access the app 

```
$ curl http://localhost:5000

{"args":{},"data":"","files":{},"form":{},"headers":{"Accept":"application/json","Host":"httpbin.org"},"origin":"101.96.66.43, 101.96.66.43","url":"https://httpbin.org/delay/1"}httpbin-wrapper
```

but with _**appsody run**_ though the option are passed successfully, I am not able to access the app with ``` curl http://localhost:5000 ```

```
appsody run --docker-options "-d -e CONTAINER_PORT='3000' -e TARGET_URL='https://httpbin.org/' -e TARGET_URI='delay/1'" -p 5000:3000
```

my sample application [server.js](https://github.com/ibmcloudprivate2/httpbin-wrapper/blob/master/server.js)

what am I missing?

**Comment by kylegc** [comment]
The command looks okay to me. Can you attach the verbose `-v` output of the `appsody run` command here?

**Comment by jaricsng** [comment]
below is the command I used

```
appsody run --docker-options "-e CONTAINER_PORT='3000' -e TARGET_URL='https://httpbin.org/' -e TARGET_URI='delay/1'" -p 5000:3000
```
