### ISSUE TITLE
Enhance the CLI build process to create Homebrew bottles for macOS

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#39]
Currently, the Homebrew installer forces a build from source (even though we are not packaging any source in the installer). The build process should generate bottles for Mojave, and High Sierra (at least).

**Comment by neeraj-laad** [comment]
@chilanti Is there still some outstanding work on this issue?

**Comment by chilanti** [comment]
We should postpone this issue. It won't be possible to have bottles until we can create a pull request against the main homebrew repo.

**Comment by neeraj-laad** [comment]
Closing this as a duplicate of #417
