### ISSUE TITLE
Successive runs of `appsody stack package` fail with 'dev-local' already exists

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#396]
**Describe the bug**
The second run of `appsody stack package` fails with this message:
```
[Error] A repository with the name 'dev-local' already exists.
```

**To Reproduce**
1. Using appsody 0.4.6
2. `cd <somedirectory>`
3. `git clone https://github.com/kabanero-io/collections`
4. `cd collections/incubator/nodejs-express`
5. `appsody stack package` (this works)
6. `appsody stack package` 

**Expected behavior**
The second run of `appsody stack package` should work.

**Actual behaviour**
The second run of `appsody stack package` fails, with the message:
```
[Error] A repository with the name 'dev-local' already exists.
```

**Environment Details (please complete the following information):**
 - OS: MacOS Mojave
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**If applicable please specify:**
 - CLI version: appsody 0.4.6
 - Stack you are using: incubator/nodejs-express

**Screenshots**

**Additional context**
See complete logs:
[appsody.package.error.log](https://github.com/appsody/appsody/files/3690468/appsody.package.error.log)

**Comment by tnixa** [comment]
I'm thinking to update the `appsody stack package` command to check for an existing dev-local index and if it exists then check for the current stack in the index and if it exists then overwrite the entry or if it doesn't exist then append a new entry.

**Comment by kylegc** [comment]
@tnixa I agree with above. And then skip the call to `appsody repo add` if dev-local has already been added.

**Comment by nastacio** [comment]
Thanks everyone, really timely, ahead of an upcoming workshop.
