### ISSUE TITLE
Allow developers to override single stack files 

### ISSUE THREAD

**Issue by kewegner** [appsody/appsody#40]
Per SD.

It will be unavoidable for application developers to (temporarily) override single files that are defined in the stacks (e.g. pom.xml for Maven).

We should change the mount behavior to use the stack-defined files, and single, overridden files if existent in the project.
This requires a more complex mounting, since a simple Docker volume would always override contents from directories recursively.
Thus, if, for example, the directory ./src/main is mounted from the application project into the stack container, it would override a definition of ./src/main/liberty/config/server.xml that originates from the stack project.

Per @seabaylea 
We could support something like a --force <path> option which mounts the provided path (file of directory) into the app

Per @neeraj-laad 
I can envision that we might need this ability. However, I'm not sure if I have completely understood the use case for doing this.

One of the biggest features for Appsody will be how a stack provider can specify what users can override/change. We would have to be very careful when we allow users to change other aspects ones that the provider does not want to change. I'd try to avoid this completely if possible.

Am I missing something here?

Per SD:
I see your point and generally I agree. However, not having a possibility to override even single files is IMO a bit too idealistic for real-world projects.

For example, if folks in the Java space need another (temporary) test dependency in their pom.xml, or something like that, if they temporarily want to change things they should have this option without immediately going the "fork stack -> make changes -> rebuild -> retest" way.

That being said, originally I would have gone for the option of "just taking and optionally overriding what the user throws into the project", but given the fact that we do want to provide opinionated ways where an override is an exception, probably an explicit way like @BAILEYC describes is the better approach.

Per @neeraj-laad 

Sure, I see your point. We will keep the issue open and will revisit this after our initial MVP, when we start looking at more advanced scenarios. Please let me know if you disagree.

Per SD:

Hmm.. I think I do see that as a quite viable point (at least for real-world projects), but yes, there are certainly other higher prio tasks being open.

**Comment by ebullient** [comment]
For Spring, we opted to mount the project folder in a nested location, and give Jane full access to the pom.xml so all the normal maven stuff works as expected. We enforce required behaviors using a parent pom provided by the stack.

**Comment by neeraj-laad** [comment]
I would like to close this issue for now. We can re-open and work on this once we see a real concrete example that justifies the extra complexity that will be needed.

Please feel free to re-open if you disagree.
