### ISSUE TITLE
Read local git information and apply labels to docker build image

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#404]
We need to gather git information to store with the stack image and appsody build image. This task is to write code functions to gather git information from the `git` command line.
- repo url
- branch
- commit
- modifications not committed

**Comment by neeraj-laad** [comment]
@kewegner perhaps we just need to indicate if there are uncommitted modifications or not, ant not worry about listing them?

**Comment by kylegc** [comment]
I agree. Kim for now, just provide us a func which returns a boolean on whether or not changes have been made after the commit.
