### ISSUE TITLE
Append labels to app-deploy.yaml 

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#405]
~~Update the `appsody build` command to always generate a new app-deploy.yaml.~~
~~This deprecates the existing app-deploy.yaml files, and the generation in `deploy` phase.~~ Moved to #517
For this iteration, we will continue to use the app-deploy.yaml from the stack or current dir and append the labels to it in the `appsody deploy` command.

The command should read all labels from the image built by appsody build. TBD exactly which labels will get written and the final format.

This should also guarantee that successive runs of `appsody deploy` command will result in updated application image to be deployed. (reported in #261). This may require inserting the image SHA to the deploy spec.

**Comment by kylegc** [comment]
@EnriqueL8 I believe we agreed with Chris's proposal to generate this on the `build` phase instead of `deploy`. I'm updating this issue's title and description to reflect that.

**Comment by neeraj-laad** [comment]
@kylegc One thing that I was not sure on was how we deal with all current deploy flags.. Eg. --knative etc. 

My concern is that some of the option names make sense for deploy but not sure if they will be for build.

**Comment by kylegc** [comment]
I think `deploy` will always do an implicit `build` so when calling `deploy` it can pass the flags through.

Supporting `--knative` on the `build` command does seem a bit odd at first, but 1) I don't think it will be used very often because most people will use the `deploy` command instead, and 2) think of it as "building for knative" and it isn't so bad.

**Comment by EnriqueL8** [comment]
This work has been completed.
