### ISSUE TITLE
Update build command to combine labels from stack image and .appsody-config.yaml and apply them to the application image

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#406]
Edit the `appsody build` command to apply the labels to the built image.

TBD exactly which labels will be written.

If stack and app have the same label but different values, which one wins?

**Comment by neeraj-laad** [comment]
@EnriqueL8 @kylegc Can we close this issue?

**Comment by neeraj-laad** [comment]
This is now merged and in place so closing. Please reopen if there are specific elements that are not complete.
