### ISSUE TITLE
`appsody stack package` command fails on second run

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#413]
**Describe the bug**
The `appsody stack package` command fails on the second run - the command tries to add the `dev-local` repo but fails as the the `dev-local` repo already exists.

**To Reproduce**
1. Go inside a stack
2. Run `appsody stack package`
3. Run `appsody stack package` again

**Expected behavior**
The command will add the replace the existing `dev-local` repo if it already exists

**Actual behaviour**
The command will give an error if the `dev-local` repo already exists

**If applicable please specify:**
 - CLI version: 0.4.6
 - Stack you are using: rust

**Comment by Kamran64** [comment]
I think this has already been raised here: https://github.com/appsody/appsody/issues/396 - Closing.
