### ISSUE TITLE
Document Appsody CLI upgrade steps

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#42]
Include documentation for:
* `brew upgrade appsody`
* `yum update`
* `apt update`
* Windows updates

**Comment by tomleah** [comment]
Where is this going to be documented? A separate doc or within the installation or other?

**Comment by neeraj-laad** [comment]
I think there should be sections for install, upgrade, uninstall in the `Installing Appsody` doc, but open to suggestions.

**Comment by mhamwala** [comment]
I'm a +1 for having sections in the `Installing Appsody` doc
