### ISSUE TITLE
Appsody build must support pushing to an image registry

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#450]
**Is your feature request related to a problem? Please describe.**
Currently `appsody build` only stores the built image in the local docker registry cache, and requires the user to issue a`docker push` command if the image must be uploaded to a registry.

**Describe the solution you'd like**
Appsody build should include: 
1) a `--push` flag that triggers the push to the default image registry
2) a `--push-url` flag that allows the user to specify the registry URL for the image

This would enable the user to run:
`appsody build -t <my-repo>/<my-image> --push`
which would cause the image to be uploaded to the "default registry" (i.e. the registry to which the `docker` CLI is currently logged in).
Or:
`appsody build -t <my-repo>/<my-image> --push-url <registry-url>`
which causes the image to be pushed to `<registry-url>/<my-repo>/<my-image>`.

Related to #410

**Comment by skoh7645** [comment]
Do we want the `--push-url` flag to be implemented for the `appsody deploy` command as well?

**Comment by skoh7645** [comment]
This issue will track the progress of implementing `--push` for `appsody build`. We can use https://github.com/appsody/appsody/issues/451 to track implementing `--push-url`
