### ISSUE TITLE
`appsody deploy --dryrun` fails

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#454]
**Describe the bug**
`appsody deploy --dryrun` fails and returns nonzero error code

**Expected behavior**
dryrun should gracefully run, print what the command would do without doing it, and exit with a zero status

**Actual behaviour**
Here is the last part of the command output
```
Dry run skipped construction of file app-deploy.yaml
Created deployment manifest: app-deploy.yaml
Found existing deployment manifest app-deploy.yaml
[Error] Could not read app-deploy.yaml file: open app-deploy.yaml: no such file or directory
```

**Environment Details (please complete the following information):**
 - OS: macOS

**If applicable please specify:**
 - CLI version: 0.4.6
 - Stack you are using: any

**Screenshots**

**Additional context**

Once this is fixed, we need to update the deploy_test.go TestDeploySimple so it does not ignore the error.

**Comment by chilanti** [comment]
Also - that Info message "Found existing deployment manifest" is a red herring.

**Comment by kewegner** [comment]
@chilanti if you haven't started this, I spent a few minutes and tried a few things here and I believe I have something that would work.  It works with deploy_test.go and with all the flags on appsody deploy.  We can talk when there is a break from the k8s work.
