### ISSUE TITLE
Pass log level across appsody commands

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#455]
**Describe the bug**
RunAppsodyCmdExec and others do not currently pass log level argument like `rootConfig.Verbose`

**If applicable please specify:**
 - CLI version: 0.4.6
 - Stack you are using:

**Comment by kylegc** [comment]
@tnixa, we think this is done, can you find the PR which satisfied this requirement?

**Comment by tnixa** [comment]
fixed with PR #816
