### ISSUE TITLE
Appsody on K8S should not warn about missing docker pre-req

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#458]
**Is your feature request related to a problem? Please describe.**
Appsody on K8S should not check whether docker is installed and running, and should avoid warning the user about the missing pre-req.

**Describe the solution you'd like**
Suppress checking the docker pre-req when on K8S.

**Comment by sympatheticmoose** [comment]
@chilanti when you get a chance can you update this issue with a bit more information about why the check is not required on K8s, as this is a record of the change.

**Comment by chilanti** [comment]
This is a nice to have. Appsody checks pre-reqs (aka whether docker is installed), but it shouldn't be doing it when it runs on K8S since docker isn't even used. Suppressing the warning should be a simple change.

**Comment by chilanti** [comment]
@neeraj-laad  - I can take care of this, or someone in Hursley could give it a try. 
I think there are two things here:
1) If someone specifies the `--buildah` flag, the pre-req's check should be turned off
2) If the env var `APPSODY_K8S_EXPERIMENTAL` is `TRUE` - same thing. 
Looking at the code path, I think that checking the flag is probably all there is to it, because the env var causes the flag to be set.
