### ISSUE TITLE
Enforce minimum requirements for a stack version

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#46]
We might want to indicate which stack is compatible with which CLI/controller version. Need to figure out the best way to achieve this. 

Current thoughts are:

- stacks will have the responsibility to specify the minimum versions for cli, docker, k8s etc.
- appsody cli can validate and enforce these are met before we run appsody commands with this stack

**Comment by Kamran64** [comment]
Closing: This work was covered in https://github.com/appsody/appsody/pull/535 which has now been merged.
