### ISSUE TITLE
Standardize the help text for the CLI commands (and add examples)

### ISSUE THREAD

**Issue by helenmasters** [appsody/appsody#463]
The number of Appsody CLI commands has grown significantly recently and the help text for these commands could do with some standardizing and editing. I also think it would help users if we added examples (in addition to the Usage: section).

I'm putting together a proposal of what this might look like for `appsody stack create` if we can find consensus this can be rolled out across the other commands.

**Comment by helenmasters** [comment]
@neeraj-laad, suggested --help text for the `appsody stack create` command is attached below:

[Sample CLI help for stack create.docx](https://github.com/appsody/appsody/files/3734715/Sample.CLI.help.for.stack.create.docx)

**Comment by doveye** [comment]
- I think the examples would be best on a line by themselves, with explanation underneath.
- Is the "string" part of the flag necessary? I'm thinking it might be clearer to say what's needed there rather than in the explanation
- I think flag explanations might be better distinguised by a capital letter at the start
Questions for global flags:
- What's the config file (do we need to mention more about it here or can we assume users will know what it is?)
- What's dry run mode (and ditto re do we need to mention more about it here)?
- What's the name of the verbose log file? In case the user needs to find it amongst a load of other log files)

--------

```
Examples:
`appsody stack create myStack`
Creates a copy of the example stack, “samples/sample-stack”, called myStack.

`appsody stack create myStack --copy incubator/nodejs-express`
Creates a copy of the Node.js.Express stack, called myStack.

Usage:
 `appsody stack create <name> [flags]`
where <name> starts with a letter or number, and can contain only lowercase letters, numbers, or dashes.

Flags:
  --copy <repository_name>/<stack_name>   Copies the specified stack. The default value is “samples/sample-stack”.
   -h, --help                             Prints this help information

Global Flags:
   --config <filename>      Specifies a configuration file. The default file is $HOME/.appsody/.appsody.yaml
   --dryrun                 Turns on dry run mode
   -v, --verbose            Turns on debug output and logging to a file in $HOME/.appsody/logs
```

**Comment by helenmasters** [comment]
Note to self, the example stack name has capital letters which contravenes our stack naming convention so I need to change it!

**Comment by helenmasters** [comment]
I hope this version addresses all the requested changes (excluding questions from @doveye about global flags). I've changed the tense on the flags back to 'Copy', 'Print' etc as this seems to be the tense universally adopted by other CLIs (Docker, man pages, Helm etc).

[Sample CLI help for stack create v3.docx](https://github.com/appsody/appsody/files/3738412/Sample.CLI.help.for.stack.create.v3.docx)

**Comment by neeraj-laad** [comment]
@doveye Trying to answer your questions on global flags here:

In general, these are flags on the appsody cli that user can set if they do not want to use the default location for config file, logging level etc. These should be described in details in a central place and not with every single command I think.

**Comment by neeraj-laad** [comment]
[Sample.CLI.help.for.stack.create.v4.docx](https://github.com/appsody/appsody/files/3738869/Sample.CLI.help.for.stack.create.v4.docx)
I've tried to suggest few changes.. but they are more specific to this particular command vs a general format for all commands.

**Comment by helenmasters** [comment]
Thanks @neeraj, your changes have been incorporated and yes after Bazif investigated the default value is specified like that with Cobra/Go.

I'll get Bazif to incorporate the relevant text snippets for `appsody stack create` into his PR.

The global flags I'll revisit.

[Sample.CLI.help.for.stack.create.v5.docx](https://github.com/appsody/appsody/files/3739079/Sample.CLI.help.for.stack.create.v5.docx)

**Comment by neeraj-laad** [comment]
@helenmasters  can we close this issue now or do you want to use this for screening through and improving rest of the help text?

**Comment by helenmasters** [comment]
@neeraj-laad it would be nice to make this an epic and hang off it individual issues to improve the help text for the other Appsody CLI commands. I am imagining that we could have issues to address each of the following:

appsody build	- Locally build a docker image of your appsody project
appsody completion	- Generates bash tab completions
appsody debug	- Run the local Appsody environment in debug mode
appsody deploy	- Build and deploy your Appsody project to your Kubernetes cluster
appsody extract	- Extract the stack and your Appsody project to a local directory
appsody init	- Initialize an Appsody project with a stack and template app
appsody list	- List the Appsody stacks available to init
appsody operator	- Install or uninstall the Appsody operator from your Kubernetes cluster.
appsody ps	- List the appsody containers running in the local docker environment
appsody repo	- Manage your Appsody repositories
appsody run	- Run the local Appsody environment for your project
appsody stack	- Tools to help create and test Appsody stacks
appsody stop	- Stops the local Appsody docker container for your project
appsody test	- Test your project in the local Appsody environment
appsody version	- Show Appsody CLI version
