### ISSUE TITLE
Support kubectl semantics of namespace in metadata of deployment manifest

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#464]
With kubectl, you can define a namespace for your deployment in the deployment manifest or via a command line option to `kubectl apply`. If both these options are used, and the namespace differs, then an error is generated.

With appsody deploy, it appears that although you can define a namespace in the metadata of app-deploy.yaml, unless you also use the` --namespace` cmd line option, this doesn't work. This appears to be because if you do not supply a `--namespace` option, to `appsody deploy`, it will add an explicit `--namespace default `to the eventual `kubectl apply` command. The `appsody deploy delete` actually gives you the smoking gun:

```
$ appsody deploy delete
.
.
Deleting deployment using deployment manifest app-deploy.yaml
Attempting to delete resource from Kubernetes...
Running command: kubectl delete -f app-deploy.yaml --namespace default
[Error] error: the namespace from the provided object "i2" does not match the namespace "default". You must pass '--namespace=i2' to perform this operation.
```

The same problem occurs on the original deploy (although the error message isn't as clear).

I expected, if I chose, to be able to define the namespace in the metadata, and have that used throughout, without any need for command line options

As an aside, I would expect an explicit declaration mismatch of namespaces to cause an error, e.g.:

`appsody deploy --namespace foo`

would fail if the metadata in the app-deploy.yaml specified a different namespace.

**Comment by kylegc** [comment]
Thanks for the write-up Henry. I agree this needs to be addressed. We are changing the way we generate the `app-deploy.yaml` as part of epic #425 which may already address this issue. However, I'll link this as a child to the epic so we keep an eye on it.

**Comment by neeraj-laad** [comment]
@EnriqueL8 Can we ensure this is addressed as part of the deploy changes you are working on.
