### ISSUE TITLE
Testing enhancements

### ISSUE THREAD

**Issue by djones6** [appsody/appsody#485]
Ideas for testing improvements:
- Write output of unit tests to logfiles to declutter the test output
- Tests should operate in their own sandbox (eg. dedicated appsody config directory) so they are not sensitive to a user's local appsody environment + can be cleaned up easily
- CLI tests should use a dedicated 'test stack' so as not to depend on specific stacks
- tests of combined CLI + stacks should be moved to a separate 'integration' test bucket

**Comment by kylegc** [comment]
* Review the CLI code coverage and identify functions that are not tested.

For example, we just had a regression bug appear (https://github.com/appsody/appsody/pull/488)
This would not have happened if there was an automated test for the imageRepo config.

**Comment by kylegc** [comment]
WRT improving the test output, I've already done some playing around with that and have a prototype. I'll create a PR and you can take it from there.

**Comment by djones6** [comment]
Closing as complete:
Decluttering test output: https://github.com/appsody/appsody/pull/639
Sandboxing tests: https://github.com/appsody/appsody/pull/640

@kylegc / @tnixa Further issued could be raised if appropriate for work on integration tests, as the PRs above do not address that area.
