### ISSUE TITLE
appsody init following a package, causes a long delay in docker pull

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#486]
We also had the issue with a new stack them meant the init/run etc. would fail to find it in the remote repositories - hence supporting IFNOTPRESNET.

However, things have got worse with the new "package" command. If I try and init (following a package command) without IFNOTPRESENT, then the docker pull hangs for quite a while, then returns with `Error response from daemon: Get https://dev.local/v2/: Service Unavailable`. It does then go on and get the locally cached version...but there is a significant delay. Looks to me like some kind of artifact of changing the  image name?

**Comment by kylegc** [comment]
@tnixa can you reproduce and investigate this please?

**Comment by tnixa** [comment]
@henrynash FYI with the fix for this we are going to change `appsody stack package` to create a `dev.local` repo instead of `dev-local` to be more consistent

**Comment by neeraj-laad** [comment]
The PR has been merged and will be part of the next cli release. Closing the issue.
