### ISSUE TITLE
Define the scope/scenarios for integration testing

### ISSUE THREAD

**Issue by kilnerm** [appsody/appsody#495]
Currently there is no automation around the pre-release integration testing.

The current testing follows the test plan here... https://github.com/appsody/appsody/blob/master/docs/testing/operator_test_plan_v3.md

We need to look at creating a test framework that provides an easy way to perform the pre-release testing and then look at integration with the component test buckets.

**Comment by neeraj-laad** [comment]
@tnixa Can we document what we intend to cover with the integration testing and provide a link here.
Once that is done can this be closed?

**Comment by tnixa** [comment]
It is documented here:
https://ibm.ent.box.com/notes/551578018754

Integration Testing - 
a. Definition: Tests latest CLI and stack code on all combinations of CLI commands and stacks on all environments
b. Assumptions:
  i. latest CLI code
  ii. latest Stack code
c. Implementation:
  i. Some kind of test framework
d. Potential Environments
  i. OS
    1. Windows
    2. Mac
    3. Linux
  ii. Containerization
    1. Docker
    2. Buildah
  iii. Deployments
    1. Open Shift
    2. Minikube
    3. Docker for Desktop
e. Improvements:
  i. Figure out test framework
