### ISSUE TITLE
Darwin builds cannot resolve vpn hosts 

### ISSUE THREAD

**Issue by s1cyan** [appsody/appsody#508]
**Describe the bug**
svt found while wfh that our kabanero cli when using a vpn, we would hit an error where the host could not be resolved. Solution provided below

**To Reproduce**
1. For any command that takes a url, pass in a url that is internal and needs a vpn to reach. 
You see a cannot resolve host error like so:
```
○ → appsody repo add foo  <ip that needs vpn>
[Error] Get <ip that needs vpn> dial tcp: lookup <ip that needs vpn>: no such host
```

**Expected behavior**
Regular Error output, not no such host

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**
 - OS: osx

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Additional context**
Solution: The darwin binary needs to be build in an osx environment with the environment variable `CGO_ENABLED=1`. Thus cross compilation of builds on travis on linux doesn't really work for the osx builds. I added `CGO_ENABLED=1` to the env vars in the travis yaml and also split the deploy/package step to do the darwin builds on osx on travis. 
See issue and PR for more detail on problem and solution:
Original VPN issue: https://github.com/kabanero-io/kabanero-command-line/issues/98
Travis fix issue: https://github.com/kabanero-io/kabanero-command-line/issues/104
PR: https://github.com/kabanero-io/kabanero-command-line/pull/106

**Comment by kylegc** [comment]
Thanks Claudia, I'll put this on our backlog to get investigated.

**Comment by chilanti** [comment]
We are debating on how to address this issue, since we just discovered that - with `CGO_ENABLED=1` - Appsody can't run on a whole lot of Linux images, including `busybox` and `alpine`.
In fact, the Linux binaries are generated by Travis with the `CGO_ENABLED=1` - and we are being asked to turn that flag off.

**Comment by s1cyan** [comment]
@chilanti  i believe this issue has only been for the osx builds. I was also thinking about fine tuning the .travis.yaml to only use CGO_ENABLED=1 for just osx for our cli.

**Comment by neeraj-laad** [comment]
Looks like this has been resolved.
