### ISSUE TITLE
"appsody run" should allow user-specified volume mounts

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#509]
**Is your feature request related to a problem? Please describe.**
Service instances in Kubernetes are invariably mapped to [Kubernetes secrets](https://kubernetes.io/docs/concepts/configuration/secret/) , which are made available to applications in different ways, such as environment variables and volume mounts.

`appsody run` can accept environment variables with `--docker-options=--env-file...` or  `--docker-options=-e...` , but there is no way to hand it files containing secrets pulled out of a container.

**Describe the solution you'd like**
I don't want to prescribe the final design, but at the most basic level, I would like for `appsody run` to stop blocking "-v" mounts inside `--docker-options`.

I would welcome a consistency check between secret references in app-deploy.yaml and options specified for `appsody run`, such as:

```
WARNING: Your deployment spec has an env var named "ABC" and your run did not specify "ABC".
```

**Describe alternatives you've considered**
There are no alternatives. If an application needs to access a secret during runtime, the lack of user-specified mounts dictates the usage of secrets as environment variables during development, and therefore, virtually dictates the same approach when the application is running in production.

**Additional context**
Incidentally, the Appsody Application Operator allows the usage of secrets as both environment variables and as volume mounts when the application runs in a cluster.

**Comment by kylegc** [comment]
Appsody depends on a number of mounts for itself and the stack to work properly. In order to allow user provided mounts, we would have to ensure they do not conflict with the other mounts appsody depends on. We will investigate this further.

**Comment by GregDritschler** [comment]
@kylegc @nastacio I would like to second the motion to allow user-specified mounts.  I tried to use the git-commit-id-plugin maven plugin to capture git repo information in my build.  It does not work because the .git folder in the project is not mounted into the container.  From what I understand this is a popular maven plugin so I imagine others will eventually have this issue.

https://github.com/git-commit-id/maven-git-commit-id-plugin

Of course the problem also could be solved by just having `appsody run` and `appsody build` automatically mount the .git folder.

**Comment by kylegc** [comment]
@GregDritschler thanks for the info. Would you please open a new issue for this? I think this is something that should be addressed by the stack itself. Make sure to specify which stack you are using. Thanks

**Comment by GregDritschler** [comment]
I did some more investigation and found out this problem is specific to java-microprofile.  I opened https://github.com/appsody/stacks/issues/504.

**Comment by nastacio** [comment]
@GregDritschler can you share the results of investigation? I just ran a quick test on nodejs-express stack and hit the same. The check seems to be coming from appsody itself:

```
 appsody run --docker-options="-v /Users/nastacio/tmp:/pa"
Running development environment...
Pulling docker image appsody/nodejs-express:0.2
Running command: docker pull appsody/nodejs-express:0.2
0.2: Pulling from appsody/nodejs-express
Digest: sha256:bc8f8de653cfca5175dd45f7fcc810a5562778e9ad59c12f2447af80461cef97
Status: Image is up to date for appsody/nodejs-express:0.2
docker.io/appsody/nodejs-express:0.2
Running command: docker run --rm -v appsody-controller-0.3.1:/.appsody appsody/init-controller:0.3.1
Unable to find image 'appsody/init-controller:0.3.1' locally
0.3.1: Pulling from appsody/init-controller
0f8c40e1270f: Pulling fs layer
6517ea7083bf: Pulling fs layer
0f8c40e1270f: Verifying Checksum
0f8c40e1270f: Download complete
6517ea7083bf: Verifying Checksum
6517ea7083bf: Download complete
0f8c40e1270f: Pull complete
6517ea7083bf: Pull complete
Digest: sha256:9316e896c3336c713fc7bf4c08d8b955c7f139e44ede8deb4c952ee0d3481b19
Status: Downloaded newer image for appsody/init-controller:0.3.1
testing docker options [-v /Users/nastacio/tmp:/pa]
[Error] -v is not allowed in --docker-options
```

**Comment by GregDritschler** [comment]
@nastacio Sorry I was referring to the problem I reported, which I thought could be solved with user-specified mounts.  It looks like that problem is a stack problem though.

**Comment by nastacio** [comment]
@neeraj-laad , I am upping this issue based on more comments from users about not being able to reuse JSON configuration files during local development without first converting them into an environment file, namely by using constructs like this:

```
echo "config=$(cat myconfig.json | tr -d "\n")" > appsody-myconfig.json
```

Then using `appsody-myconfig.json` inside `appsody --docker-options="--env-file=appsody-myconfig.json" and modifying the code to get the json string from the file before processing the configuration.

**Comment by nastacio** [comment]
@neeraj-laad

Upping the thread again, sorry for being pushy on this one, but it keeps coming up for the more serious users.

Pretty please for the next release?  :-)

**Comment by alohr51** [comment]
Ran into this while trying to convert an application to use appsody. I would def like this feature as well as it would make development possible.

Our use case is we have  an optional feature that is enabled depending on if a secret is injected into the container. We can't test this feature in development if we can't mount it into the container during appsody run.

**Comment by makandre** [comment]
Hi, I'm curious, how are these user-specified mounts treated when appsody is running on Kube (e.g. in Che?) @neeraj-laad @skoh7645
