### ISSUE TITLE
Cannot retrieve controller

### ISSUE THREAD

**Issue by edewit** [appsody/appsody#51]
Doing the following I get this error:
```
$> appsody init nodejs-express
Running appsody init...
Downloading nodejs-express template project from https://github.com/appsody/stacks/releases/download/0.2.0/incubator.nodejs-express.templates.simple.tar.gz
Download complete. Extracting files from nodejs-express.tar.gz
Setting up the development environment
Running command: docker[pull appsody/nodejs-express:0.2]
Running command: docker[run --rm --entrypoint /bin/bash appsody/nodejs-express:0.2 -c find /project -type f -name .appsody-init.sh]
Successfully initialized Appsody project
$> appsody run                
Running development environment...
Running command: docker[pull appsody/nodejs-express:0.2]
[Error] Cannot find source file /home/edewit/bin/appsody-controller to copy
[Error] Cannot retrieve controller - exiting: stat /home/edewit/bin/appsody-controller: no such file or directory
```
`/home/edewit/bin` is where I have the appsody command installed

**Comment by seabaylea** [comment]
Hi @edewit would it be possible for you to run `stat /home/edewit/bin/appsody-controller` and paste the output?

**Comment by seabaylea** [comment]
Essentially, as well as the `appsody` CLI, you should also have an `appsody-controller` that controls the lifecycle of your application.

**Comment by chilanti** [comment]
How did you install Appsody? If you used one of the installers, the controller would be deployed as well. If you attempted to build from source, it's your responsibility to also build the controller and deploy it in the same directory as the appsody CLI. I would suggest using one of the installers that are provided as described [here](https://appsody.dev/docs/getting-started/installation).

**Comment by edewit** [comment]
@chilanti ahh right, I took the `appsody-0.2.2-linux-amd64.tar` from the release page. Now I've used the RPM and all is good thanks
