### ISSUE TITLE
Repo names are inconsistent in appsody list output 

### ISSUE THREAD

**Issue by sriniketana** [appsody/appsody#511]
**Describe the bug**
Running the appsody list command displays stacks with half of them showing the repo name as `appsodyhub` and the other half as `experimental` 

**To Reproduce**
Run `appsody list` 

**Expected behavior**
1. The name of the repo is technically appsodyhub and it should show so. experimental is not correct. 
2. There should be a way to display the branch too. Add another column 
3. Commands such as `appsody stack create` expect the stack name in the format <repo>/stackname>. Such commands should be modified too

**Actual behaviour**
Actual output 

```srik:myownstack srihari$ appsody list 

REPO        	ID                       	VERSION  	TEMPLATES        	DESCRIPTION                                                 
appsodyhub  	java-microprofile        	0.2.18   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven   
appsodyhub  	java-spring-boot2        	0.3.15   	*default, kotlin 	Spring Boot using OpenJ9 and Maven                          
appsodyhub  	nodejs                   	0.2.5    	*simple          	Runtime for Node.js applications                            
appsodyhub  	nodejs-express           	0.2.7    	scaffold, *simple	Express web framework for Node.js                           
appsodyhub  	nodejs-loopback          	0.1.5    	*scaffold        	LoopBack 4 API Framework for Node.js                        
appsodyhub  	python-flask             	0.1.4    	*simple          	Flask web Framework for Python                              
appsodyhub  	starter                  	0.1.0    	*simple          	starter sample stack that can be run by appsody, to help    
            	                         	         	                 	creation of more stacks                                     
appsodyhub  	swift                    	0.1.4    	*simple          	Runtime for Swift applications                              
dev-local   	myownstack               	0.2.7    	scaffold, *simple	Express web framework for Node.js                           
experimental	java-spring-boot2-liberty	0.1.10   	*default         	Spring Boot on Open Liberty & OpenJ9 using Maven            
experimental	nodejs-functions         	0.1.4    	*simple          	Serverless runtime for Node.js functions                    
experimental	quarkus                  	0.1.5    	*default         	Quarkus runtime for running Java applications               
experimental	rust                     	0.1.2    	*simple          	Runtime for Rust applications                               
experimental	vertx                    	0.1.3    	*default         	Eclipse Vert.x runtime for running Java applications```

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**If applicable please specify:**
 - CLI version: 0.4.7

**Comment by neeraj-laad** [comment]
I agree we should change `appsodyhub` to `incubator`

**Comment by kylegc** [comment]
I'm confused here. What is incorrect about `experimental`?

**Comment by sriniketana** [comment]
@kylegc - Technically, `appsodyhub` is the name of the repo and `stable`, `incubator` and `experimental` are branches within the repo. 
Every repo has those 3 branches - so if I were to use `experimental/stackname`, it doesnt tell me which repo to use.

**Comment by kylegc** [comment]
Actually `stable`, `incubator`, and `experimental` are all three separate repositories. They all have separate index files and you can use `appsody repo add/remove` to add them with any name you'd like. 
(Also see `appsody repo list`)

`appsodyhub` happens to be the default name for the incubator repository, but I think @neeraj-laad is proposing to change that above.

**Comment by sriniketana** [comment]
Makes sense. Renaming `appsodyhub` to `incubator` should do the trick

**Comment by neeraj-laad** [comment]
I agree user can add one of our public repos (experimental, incubator, stable) with any name. I just think that using the term `hub` to describe a repository is confusing. If we are adding repositories as part of our default configuration, we can start with the repository name as the name.

Users are able to change this if they want something else but will probably be cleaner.

@kylegc do you agree?

**Comment by kylegc** [comment]
I agree. I've put in PR #521 to change the default from `appsodyhub` to `incubator`.

Now the question is: should we add code to migrate existing user's configuration? If not, users will be stuck with `appsodyhub` until they remove it manually or delete their ~/.appsody directory.

**Comment by Kamran64** [comment]
I think it would be a little bit confusing if half our user base has an `appsodyhub` repo whilst the other half has `incubator`. Plus I'm not sure how many currently remove repos via deletion of the `~/.appsody` folder rather than using `appsody repo remove` (but I could be wrong). Also, thinking about how a user would follow the docs also since we'll only be referring to one or the other.

**Comment by neeraj-laad** [comment]
@kamran you have a valid point, but we cant stay with `appsodyhub` to avoid that problem.  I thnk we need 3 things: 

1. Set the default name for repo to `incubator` (all new users will be with this)
2. Migrate/update existing config for current users to update the name of default incubator repo from appsodyhub to incubator.
3. Update all docs / blogs to new name.

**Comment by Kamran64** [comment]
@neeraj-laad - Sorry I should have clarified in my previous comment. I think we should change the name but also migrate the existing configuration as opposed to wait for users to delete their `~/.appsody` folder for the reasons mentioned above.

However, I wasn't sure how feasible it would be to do that but if you say we've done it before then maybe migration isn't as tricky as I thought...

**Comment by neeraj-laad** [comment]
For migration, we are relying upon that users will be upgrading to the latest cli (which has the migration capability). But, I hope that with us constantly prompting users to upgrade we can take that call and go ahead with rename.
