### ISSUE TITLE
Stack image labels should point to stack specific readme or folder in github

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#516]
The following oci labels point to github URLs:
```
"org.opencontainers.image.url": "https://github.com/appsody/stacks", 
"org.opencontainers.image.documentation": "https://github.com/appsody/stacks",
"org.opencontainers.image.source": "https://github.com/appsody/stacks/tree/master",
```

These URLs should drill down into the repo to point to the specific stack.
"documentation" should point specifically to the readme file.

**Comment by EnriqueL8** [comment]
As a suggestion, we could add a field to `appsody-config.yaml` where the user can specify the location of such documentation. This will also enable the user to point to an external location such as a website, instead of always pointing to a `README.md` file.

**Comment by kylegc** [comment]
@EnriqueL8 your suggestion makes sense for appsody projects and the labels generated on `appsody build`. However, this issue is specifically for stack images and the `appsody stack package` command. For now we are requiring every stack to have a README and there shouldn't be any external documentation.
