### ISSUE TITLE
Json output does not show correct name

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#523]
**Describe the bug**

I removed the `experimental` repo and added it back with a different name.  When I do `appsody repo list -o json`, the name shown is the original name, not the name I used to add it:

![image](https://user-images.githubusercontent.com/17596240/67603458-f31c4b80-f746-11e9-8e56-6bf11d8e4ee7.png)

The output for `appsody list -o json` also shows the original `experimental` name.

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version: 0.4.7
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by makandre** [comment]
Just one to confirm one other thing: if I added a repo using a custom name, i.e. `custom`, then when I init something from that repo, it would be `appsody init custom/<stack>`, is that right?

**Comment by Kamran64** [comment]
Yep, that's right @makandre
