### ISSUE TITLE
Modify `appsody stack package` command to tag docker images with stack version

### ISSUE THREAD

**Issue by groeges** [appsody/appsody#526]
**Is your feature request related to a problem? Please describe.**
The `appsody stack package` command generates the docker images using a tag of `SNAPSHOT`. The appsody CI scripts will be using the `appsody stack package` command to generate the release images and as such it needs to be able to generate the docker images which are tagged with the full version information. 
 
**Describe the solution you'd like**
The `appsody stack package` command will tag the docker images with full version info and not use SNAPSHOT.

As the `appsody stack validate`  needs to test the local images and not to pull the remote docker hub images, it will need to set the APPSODY_PULL_POLICY=IFNOTPRESENT variable before testing.

**Describe alternatives you've considered**

**Additional context**

**Comment by nastacio** [comment]
Please consider creating all variations of the tag for [semantic versioning](https://semver.org/) testing, i.e.:
imagename:MAJOR
imagename:MAJOR.MINOR
imagename:MAJOR.MINOR.PATCH

E.g. ./ci/build.sh currently generates these for a stack with version 0.2.10 in stack.yaml

```
appsody/java-microprofile-dev-mode            0                            e1dc72758920        ...
appsody/java-microprofile-dev-mode            0.2                          e1dc72758920        ...
appsody/java-microprofile-dev-mode            0.2.10                       e1dc72758920        ...
```

**Comment by kylegc** [comment]
@nastacio yes that's the plan!

**Comment by nastacio** [comment]
@groeges , @kylegc 

I see it in 0.5.0, somehow I missed it in the release notes.

With this final (at least for me) addition to the `appsody` CLI, we have a much cleaner experience for stack developers, specially for Windows users who had a hard time with python/pip setup. 

PS:  Really nice touch with `--image-namespace`
