### ISSUE TITLE
deploy: tried to "docker push" when no tag is specified

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#529]
**Describe the bug**
When running `appsody deploy --push` without specifying a `--tag`, the command will set the tag to `dev.local/<project-name>` and try do the a `docker push` (which fails). 

**To Reproduce**
1. Run `appsody deploy --push` an any appsody project
2. See error `Could not push the docker image - exiting. Error: exit status 1`

**Expected behavior**
If the user does not specify the necessary `--tag`, do not try to run `docker push`, give a warning message to skip the command instead

**Actual behaviour**
CLI tried to do `docker push`

**If applicable please specify:**
 - CLI version: 0.4.7
 - Stack you are using: nodejs-express

**Screenshots**

**Additional context**

**Comment by chilanti** [comment]
Agreed - we should warn. This is a known behavior, but it might be confusing.

**Comment by chilanti** [comment]
After some discussions, we decided to check up front if `--push` or `--push-url` are used without `--tag`, and error out if that's the case.
