### ISSUE TITLE
Machine readable output for list/repo list

### ISSUE THREAD

**Issue by BarDweller** [appsody/appsody#53]
**Is your feature request related to a problem? Please describe.**
I want to script installation of a repo, and verification of the stacks contained within.
Today, this involves passing the human formatted output from appsody list/repo list through grep/sed/cut etc to extract & identify the info by line/column/regex etc. 
This approach is obviously fragile, and less than ideal.

**Describe the solution you'd like**
kubectl offers `-o json` .. I'd like to see something like this for appsody, to enable scripts to parse appsody query command output

**Describe alternatives you've considered**
An alternative could be to allow selection of the fields to be output, and if headers should be included etc. This approach is used for other unix commands, eg, `ps` supports `-h` to suppress headers, and other args to allow selection of columns.. This makes the output from ps easier to handle within scripts etc, at the cost of making the flags for the interface kind of complex.

**Additional context**
Without any current flags to produce this kind of output, it should be considered that the current text format is likely to be parsed by scripts, and thus changes to such should be very carefully considered due to potential impact to tooling.

**Comment by kylegc** [comment]
Thanks for the details. I think this is a valid requirement. I'll add it to the backlog to be implemented.

**Comment by BarDweller** [comment]
FWIW, parsing `appsody repo list` if the repo names contain spaces is a REAL pain.
