### ISSUE TITLE
Move the app-deploy.yaml generation to the build command

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#536]
The `app-deploy.yaml` file is currently generated/updated on the `appsody deploy` command. We should instead generate this on the `appsody build` command because all of the information is available at this time and allows users/ci pipelines to skip the `appsody deploy --generate-only` command.

After this change, the deploy command will simply
1. run build (passes all the flags)
2. run kubectl apply

Some flags, such as `--pull-url` will have to move to be added to the build command.
The deploy `--generate-only` will be deprecated. If this is specified, only run build.

**Comment by EnriqueL8** [comment]
As part of this issue we could explore using `v1beta1.AppsodyApplication` instead of our local `AppsodyApplication`.

**Comment by neeraj-laad** [comment]
@EnriqueL8 @kylegc Can we close this issue?

**Comment by EnriqueL8** [comment]
Yes
