### ISSUE TITLE
Stack linter should check for valid license values

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#558]
**Describe the bug**
Currently, the linter does not check if the license value is a valid SPDX license ID (https://spdx.org/licenses/). We must check that users specify an accurate value for this field as part of linting the stack - `appsody stack lint`

**Comment by kylegc** [comment]
Does this issue also apply to the `license` field in `.appsody-config.yaml`? We should either handle that here or in another issue.

We should also check that the `license` field is a valid kubernetes label value. I've already done this for the `.appsody-config.yaml` but not the `stack.yaml`.
See utils.go `IsValidKubernetesLabelValue()` func.

**Comment by skoh7645** [comment]
@kylegc thanks, I have made the relevant changes to the PR
