### ISSUE TITLE
Update publish location for cli docs

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#56]
We have merged the docs repository into the website repository to simplify contributor experience for appsody docs:

As a result, we need to update the cli doc publish location to: 
https://github.com/appsody/website/blob/master/content/docs/using-appsody/cli-commands.md

**Comment by kewegner** [comment]
The following changes will be made to the docs-build/deploy.sh script:

Make the following changes:

git clone https://${GH_TOKEN}@github.com/${GH_ORG}/website.git

cd website

diff ../../build/cli-commands.md ./content/docs/using-appsody/cli-commands.md

cp ../../build/cli-commands.md ./content/docs/using-appsody/cli-commands.md

git add content/docs/using-appsody/cli-commands.md

**Comment by kewegner** [comment]
Finished under the PR above.
