### ISSUE TITLE
Appsody on K8s: support debugging scenario

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#561]
**Is your feature request related to a problem? Please describe.**
Appsody on K8S is untested with regard to the ability to provide remote debugging and to run `appsody debug`.

**Describe the solution you'd like**
Test and enable the `appsody debug` scenarios.

**Comment by neeraj-laad** [comment]
We have done initial work on this but this depends on how CodeWind plans to support debugging scenarios.

**Comment by kylegc** [comment]
Work started but not merged in PR #624
