### ISSUE TITLE
Specifying --push-url on deploy should assume --push

### ISSUE THREAD

**Issue by henrynash** [appsody/appsody#568]
The new `--push-url` and `--pull-url` deploy options are great for private image repos (like OpenShift). However, it does seem strange that if you specify a `--push-url` that you also need to actually specify `--push` to cause the push to happen. I therefore propose that if a `--push-url` is specified, the a `--push` should be implied. Here's an example of a recent deploy to OpenShift (where I had already set DOCKER_REGISTRY to the route I created to access the OpenShift registry):

`appsody deploy --tag insurance-quote/mytest:v1 --push-url $DOCKER_REGISTRY --push --pull-url docker-registry.default.svc:5000 --namespace insurance-quote`

We could, if we think there might be corner cases when you would NOT want to have an implicit push, support a `--no-push` option....but I can't really think why you would need this.

**Comment by kylegc** [comment]
@chilanti did you have a scenario where a user would want to specify a `--push-url` but not push?

**Comment by kewegner** [comment]
We will do this.  It will be in the next release later this week.

**Comment by kewegner** [comment]
Fixed in #589
