### ISSUE TITLE
Wrapping quotes around label flag in appsody build

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody#591]
## Summary
We add a series of labels to the final docker image when we build it by using the `--label` flag. These labels are formed of key-value pairs such as `key=value`. We currently do not wrap the value in quotes, and this may result in an issue if the value contains spaces. For example, `dev.appsody.stack.description=This is a description for my stack`. 
We also perfom some operations on thes values to match the Docker and Kubernetes formats, but there could be some characters that still need to be escaped when running `docker build`.

**Comment by skoh7645** [comment]
There are some cases when the git commit messages have quotation marks (e.g. `Revert "quarkus: update stack to set minimum requirements for Docker and utilise templating" (#616)`) which are not escaped. This means whilst getting the git labels, an invalid JSON is generated which cannot be unmarshalled

**Comment by EnriqueL8** [comment]
Fixed by #889
