### ISSUE TITLE
Stack create should be able to copy custom stacks

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#618]
**Is your feature request related to a problem? Please describe.**
Today we can copy a stack to use that as a basis for a new stack using the command `appsody stack create <name> --copy <base-stack>`

This has a restriction though that the base stack has to be a public appsody stack. It would be great if it could use the user's local appsody configuration and use those repos to be able to create a copy in some way.

**Describe the solution you'd like**
appsody stack create should be able to copy non-public/unofficial Appsody stacks.

**Comment by henrynash** [comment]
This would be particularly useful within private Kabanero collections - but also if we want enterprises who have bought into Appsody but not Kabanero, and are building their own private enterprise-wide Appsody Hubs/Repos, then they will absolutely need this.

**Comment by timroster** [comment]
Scratching my head as to why:
`appsody stack create custom-nodejs-express --copy kabanero/nodejs-express`
does not work and found this issue. Agree with @henrynash that an enterprise solution architect that is looking to extend a kabanero collection, even the public one, is going to get stuck on this limitation.

**Comment by kylegc** [comment]
I agree this is a problem that needs to be addressed. Unfortunately there are architectural challenges with the implementation of this that need to get sorted out first.

**Comment by neeraj-laad** [comment]
So today for a custom stack, we do know which git repo has the source for the stack to be copied. Also, there is no requirement that the stack has to be on a git repo to be in an index.

Could we include the git url for each stack in the index.yaml and use that for copying the stack over?

Initial thoughts:
`appsody stack add-to-repo` - can add path/git url for the folder that contains the stack. When running locally it sill just put the file:///url and when running as part of our CI it can add proper url.

`appsody stack create` can then lookup for this information in the user's local configuration and then use that to copy over.

@kylegc @groeges would like to get your thoughts.

**Comment by neeraj-laad** [comment]
Thinking a bit more, there were issues with when the src for a custom stack will get to a git repo with respect to the packaging of the stack. My proposal above seems to add a  dependency which might or might not be true. Moreover, stack creators might prefer to use a diff SCM system, so having that flexibility will be good.

Here's another proposal:

`appsody stack package` - should package the src folder for the stack (the folder it is packaging) and create an archive (exactly what it does for templates today). The URL for accessing this archive is also added to `src: <url>` field in the generated index.

This src gets published as part of stack release. We can keep all the handling of release-url to be same as that is for the templates.

`appsody stack create` - just copies this archive and unpacks it. This is a big simplification over the current implementations (clone the entire appsody/stacks repo and look for the folder that matches the stack repo/name and extract that out).

This means if a user can access a stack they can access the source of the stack too. and there is no distinction of which repo it is coming from. or even assuming it is coming from a git repo.

Looks like not a very radical change to me, that we can implement quickly. If we change the approach of publishing templates in future, we can take the same stance with the source too. 

@kylegc @groeges @kilnerm @ebullient would like to get some feedback on this.

**Comment by chilanti** [comment]
Neeraj and I discussed various aspects of this proposal off-line - I concur that publishing the stack source as an additional `tgz` is a good approach.

**Comment by groeges** [comment]
As Neeraj and I came upo with this proposed solution I think I am OK with this. 
As well as the mentioned changes to the CLI (`stack package` and `stack create`)  there may also be changes to  `stack add-to-repo`. There will also be updates required to the CI scripts (new issue needs to be created for this)

**Comment by CameronMcWilliam** [comment]
Included in PR #856
