### ISSUE TITLE
Check whether docker daemon has permissions required by appsody, specially on Windows

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#623]
**Is your feature request related to a problem? Please describe.**
Post-installation of Docker on Windows platform is generally painful. The daemon needs access to the drive containing the appsody projects and there are a number of `icacls` commands that need to be executed to ensure the Docker daemon has access to all Appsody folders (e.g. %USERPROFILE%\.appsody, %USERPROFILE%\...\project\diretory, and %USERPROFILE%\.m2 (if using Java).

The whole procedure is described here: https://appsody.dev/docs/docker-windows-aad/

**Describe the solution you'd like**
Ultimately, I wanted the appsody CLI to tell the user whether everything it needs from Docker is setup. That may be very tricky to achieve and would also be overly sensitive to changes in Docker configuration (possibly private) interfaces, so a good compromise would be for appsody to check what is described in the "Validating the correct permissions" section of https://appsody.dev/docs/docker-windows-aad/ , at very least, this one:

`docker run --rm -it -v "%USERPROFILE%\.appsody":/data alpine  /bin/sh  -c "mkdir /data/test-write-permission && echo Success; rmdir /data/test-write-permission"`

If that check fails, then that is a clear sign that the user did not read (or maybe missed something) in the FAQ page, which would be a perfect moment to tell the user to go read the page and execute the instructions in it.

**Describe alternatives you've considered**
The CLI itself could execute the instructions in that page, assuming it knows who is the user being used to share the drive in the Docker daemon.

**Additional context**
This is a very common problem in the initial experience for Appsody developers using Windows. In fact, even experienced users get blindsided by this problem when they create a new directory for an appsody project inside their home directory.

I do understand the resolution lies within making changes to Docker/Windows configuration, but it is Appsody who needs that specific configuration (i.e. many docker-based apps have no need to write to mounted directories inside the user home directory).

**Comment by chilanti** [comment]
This could be incorporated in the Windows setup script. Thanks for opening the issue.

**Comment by nastacio** [comment]
This is issue is being hit multiple times a week by various users, reported in the public appsody slack channel.

@neeraj-laad, @kylegc, @chilanti , is it possible for an initial plug to make into next appsody release?

At this point, what we learned is that users will not think of reading the stopgap FAQ page, or maybe not associate the cryptic error message in CLI with that FAW entry, then go straight to the forums asking for help.

**Comment by scottkurz** [comment]
I realize this is already closed and the issue merged... but...I wonder if the warning could have been more in-your-face?   E.g. to me in this output:

```
[Warning] Docker may not have the appropriate write permissions on your file system
[Warning] Please refer to https://appsody.dev/docs/docker-windows-aad/ for more info on this
Adding C:\ydosppa\appsody-0.5.1-windows\ to your Path environment variable if not already present....

SUCCESS: Specified value was saved.
```

the "Warning" is drowned out by the all-caps SUCCESS of the `setx` command :)   

I know this is an imperfect solution anyway since you could have plenty more issues, like with the app dirs you're mounting.    Still... good that we're paying attention to this..let's see how it goes.

**Comment by nastacio** [comment]
@chilanti 

I do not understand "may not have".

If the check proposed in the original issue fails, the user's environment definitely has a problem, no?

```
docker run --rm -it -v "%USERPROFILE%\.appsody":/data alpine /bin/sh -c "mkdir /data/test-write-permission && echo Success; rmdir /data/test-write-permission"
```

I like the fact that the user will be redirected to read that page, at which point the softer wording in the message will not matter as much.
