### ISSUE TITLE
Update the linter to check for valid templating values

### ISSUE THREAD

**Issue by Kamran64** [appsody/appsody#625]
**Is your feature request related to a problem? Please describe.**
When the work done by: https://github.com/appsody/appsody/pull/528 goes in, we should consider updating the `stack.yaml` linter to check for valid key:value pairs. 

**Describe the solution you'd like**
Add a check to the linter, that templating is used. If not, warn the user (but don't error), to encourage more stack creators/contributors to utilise this capability within their stack. If they have added it here, we can validate that the keys and values specified are valid for the stack (@CameronMcWilliam - Is there a strict naming requirement for what keys should be set as?)

**Comment by CameronMcWilliam** [comment]
Keys and values must be strings (for now) and keys must begin with an alphanumeric character.
