### ISSUE TITLE
appsody repo add does not ensure unique repo names

### ISSUE THREAD

**Issue by BarDweller** [appsody/appsody#64]
**Describe the bug**
`appsody repo add` allows adding of multiple repos with the same name, (even with the same url). This makes management with `appsody repo remove <name>` impossible.

**To Reproduce**
1. `appsody repo add test https://raw.githubusercontent.com/appsody/stacks/master/index.yaml`
2. `appsody repo add test https://raw.githubusercontent.com/appsody/stacks/master/index.yaml`
3. `appsody repo list`

**Expected behavior**
Appsody should either refuse to add an existing name, or should update the existing name to have the url specified. Ensuring uniqueness for repo names then allows sensible management via `appsody repo remove` etc.

**Actual behaviour**
What is the actual behaviour.
Appsody adds whatever you ask with whatever name you ask, even if it already has a repo by that name, leading to confusion with `appsody repo list` and `appsody repo remove`.

**Environment Details (please complete the following information):**
 - OS: Linux

**Screenshots**
```
user@host:~/appsody$ appsody repo add test https://raw.githubusercontent.com/appsody/stacks/master/index.yaml
user@host:~/appsody$ appsody repo add test file:///home/user/appsody/appsody/index.yaml
user@host:~/appsody$ appsody repo list

NAME    URL                                                              
test    https://raw.githubusercontent.com/appsody/stacks/master/index.yaml
test    file:///home/user/appsody/appsody/index.yaml      
user@host:~/appsody$ appsody repo remove test
user@host:~/appsody$ appsody repo list

NAME    URL                                                        
test    file:///home/user/appsody/apsody/index.yaml
```
**Additional context**

**Comment by kylegc** [comment]
Agreed. Moving to backlog.
