### ISSUE TITLE
appsody repo add allows control chars as part of repo name

### ISSUE THREAD

**Issue by BarDweller** [appsody/appsody#65]
**Describe the bug**
`appsody repo add` does not seem to care which characters are included in a repo name, even allowing control chars, making administration difficult. 

**To Reproduce**
1. use `appsody repo add` to add a repo with control chars in its name .. eg. 
```
appsody repo add $'multi\nline' file://home/user/appsodyindex.yaml
```
2. use `appsody repo list` to view the created disaster.
3. `appsody repo remove` will only function with the exact sequence used to create the repo entry, you may need to view the appsody config file to figure out what it was. 

**Expected behavior**
Ideally appsody would have a schema specifying which chars are allowed in repo names, and would reject those that do not meet the requirements.

**Actual behaviour**
What is the actual behaviour.
Appsody eats whatever you give it, including strings with embedded linefeeds, nulls, even bash color escape sequences. 

**Environment Details (please complete the following information):**
 - OS: Linux

**Screenshots**

```
user@host:~/Appsody$ appsody repo add $'\033[0;31mred\033[0m' file:///home/user/Appsody/appsody/index.yaml
user@host:~/Appsody$ appsody repo add $'\033[0;96mcyan\033[0m' file:///home/user/Appsody/appsody/index.yaml
user@host:~/Appsody$ appsody repo add $'\033[8mhidden\033[0m' file:///home/user/Appsody/appsody/index.yaml
user@host:~/Appsody$ appsody repo add $'multi\nline' file:///home/user/Appsody/appsody/index.yaml
user@host:~/Appsody$ appsody repo add $'embedded\000null' file:///home/user/Appsody/appsody/index.yaml
```
(then try `appsody repo list`)

**Additional context**

**Comment by kylegc** [comment]
Yes, we should limit the chars allowed. How about digits, numbers, dash, and underscore? e.g. regex of [a-zA-Z0-9\-_]

Perhaps we put a max char length on it too.
