### ISSUE TITLE
appsody stack add-to-repo: does not print message to show command succeeded

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#658]
**Describe the bug**
The `appsody stack add-to-repo` command does not print a message to tell users that the command has succeeded. Perhaps we should also print a message to tell users that the index file has been created user the ~/.appsody/stacks/dev.local directory (as we have in the help text).

**To Reproduce**
1. Go to base directory of a stack
2. Run `appsody stack add-to-repo my-repo`
3. Command succeeds without a success message

**Expected behavior**
IF the command succeeds we should let the users know

**Actual behaviour**
Command succeeds without message

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version: 0.5.0
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by groeges** [comment]
Should be resolved.
