### ISSUE TITLE
line 1: cannot unmarshal !!str `<pre> <...` into cmd.RepoIndex

### ISSUE THREAD

**Issue by cmoulliard** [appsody/appsody#683]
**Describe the bug**

The command `appsody repo add my-local-repo file://local-appsody-repo.yml` generates on Macos the following error:
```
appsody repo add my-local-repo file://local-appsody-repo.yml -v
[Debug] Logging to file /Users/dabou/.appsody/logs/appsody2019-11-21T12-05-31.495641.log
[Debug] Writing config file /Users/dabou/.appsody/.appsody.yaml
[Debug] Running with command line args: appsody repo add my-local-repo file://local-appsody-repo.yml -v
[Debug] Downloading appsody repository index from file://local-appsody-repo.yml
[Debug] Proxy function for HTTP transport set to: 0xc0003bc610
[Debug] Contents of downloaded index from file://local-appsody-repo.yml
<pre>
<a href=".DS_Store">.DS_Store</a>
<a href=".VolumeIcon.icns">.VolumeIcon.icns</a>
<a href=".file">.file</a>
<a href=".fseventsd/">.fseventsd/</a>
<a href=".vol/">.vol/</a>
<a href="Applications/">Applications/</a>
<a href="Library/">Library/</a>
<a href="System/">System/</a>
<a href="Users/">Users/</a>
<a href="Volumes/">Volumes/</a>
<a href="bin/">bin/</a>
<a href="com.apple.TimeMachine.localsnapshots/">com.apple.TimeMachine.localsnapshots/</a>
<a href="cores/">cores/</a>
<a href="dev/">dev/</a>
<a href="etc">etc</a>
<a href="home">home</a>
<a href="opt/">opt/</a>
<a href="private/">private/</a>
<a href="sbin/">sbin/</a>
<a href="tmp">tmp</a>
<a href="usr/">usr/</a>
<a href="var">var</a>
</pre>

[Error] Repository index formatting error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `<pre> <...` into cmd.RepoIndex
```

**To Reproduce**
1. git clone https://github.com/BarDweller/stacks.git && cd stacks
2. git checkout sb-debug-watch
3. cd ..
4. appsody stack add-to-repo sb-rhr $HOME/Temp/appsody/stacks/incubator/java-spring-boot2-rhr
5. cp  ~/.appsody/stacks/dev.local/sb-rhr-index.yaml local-appsody-repo.yml
6. appsody repo add my-local-repo file://local-appsody-repo.yml

**Environment Details (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - CLI version: 0.5.0

**Comment by EnriqueL8** [comment]
This should be fixed in #650 @groeges ?

**Comment by skoh7645** [comment]
Think this is a problem with the help text for `appsody repo add` not being clear enough, I have raised a PR to fix this: https://github.com/appsody/appsody/pull/684. 
You need to pass the absolute path to your generated index yaml (it is generated in `$HOME/.appsody/stack/dev.local`) and it will be named `sb-rhr-index.yaml` in your case (taken from the name you gave the repo in the `appsody stack add-to-repo`)

**Comment by skoh7645** [comment]
Closing this issue as we have resolved the user's problem.
