### ISSUE TITLE
Delete volume dependencies after running tests

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody#685]
**Is your feature request related to a problem? Please describe.**
Our tests create volumes for the dependencies of every stack tested, and are not deleted.

**Describe the solution you'd like**
Clean up these volumes once the tests have finished. We could use `docker volume prune` since we stop the containers during the tests.

**Comment by neeraj-laad** [comment]
We should not delete other volumes by running `prune`. We need to selectively delete the volumes that we know appsody will create.
