### ISSUE TITLE
command to list all running stacks

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#69]
I was testing the `appsody stop --name` today and I noticed I need to do a `docker ps` to figure out which stacks/images/projects were running. I think it would be helpful if we had a command that lists the currently running stacks. Could be similar to `appsody list` or maybe an added column to that output.

**Comment by neeraj-laad** [comment]
Sounds like a good idea. 

Let us flush out some more details to agree who we would want to provide this capability.

**Comment by tomleah** [comment]
We could add a label the images and then look for containers that are using labelled images

**Comment by kewegner** [comment]
If you just want to find the appsody containers, you could do this:

run the following with exec.Command.Run in golang

docker ps --no-trunc --format "{{.Names}} {{.Command}} {{.Image}}" |grep appsody-controller

The output would be as such (space delimited above, but could be anything:

appsody8-dev "/appsody/appsody-controller --mode=run" appsody/nodejs-express:0.2

Unfortunately there isn't a --filter option for command.
You could pretty  it up adding headers, getting rid of the command, etc.

**Comment by henrynash** [comment]
I'd be happy to take on this enhancement. One idea I had is that we would could model this on 'docker ps', i.e: 'appsody ps' would produce something like:

CONTAINER ID       STACK                            STATUS              NAMES
84743a7099b4      nodejs-express:0.2.2    Up 4 hours         simple2-dev
e41fd19f4389        nodejs-express:0.2        Up 7 days           cw-mynodee2-1a160320-b877

Is the idea that this would only show stacks running in the local dev environment (as opposed to those that are deployed onto a remote Kubernetes cluster)?
