### ISSUE TITLE
"appsody run" is no longer promptly responding to Ctrl+C or responding at all

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#691]
**Describe the bug**
Per [thread in appsody public channel](https://appsody.slack.com/archives/CKXDDB4A3/p1574359482149200) , appsody 0.5.0 stopped processing Ctrl+C keys in the terminal for `appsody run`

This is a major regression with significant impact across all existing documentation and guides spread across kabanero.io, tutorials, customer support material, etc

**To Reproduce**
1. Run `appsody run` for stacks like experimental/rust and incubator/java-microprofile
2. Wait for the application to complete its startup and then press "ctrl+c"

**Expected behavior**
The application used to end in a couple of seconds

**Actual behaviour**
The applications no longer stop

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina
 - Browser [e.g. chrome, safari] N/A

**If applicable please specify:**
 - CLI version: 0.5.0
 - Stack you are using: experimental/rust and incubator/java-microprofile
- Docker version (client / server) 

docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Screenshots**
![Screen Shot 2019-11-21 at 4 03 14 PM](https://user-images.githubusercontent.com/3278623/69376546-76628b80-0c78-11ea-8637-fcab66459d0c.png)
![Screen Shot 2019-11-21 at 4 04 24 PM](https://user-images.githubusercontent.com/3278623/69376646-a447d000-0c78-11ea-9480-e9a097f62441.png)

![dockerdesktop-version](https://user-images.githubusercontent.com/3278623/69377843-0d304780-0c7b-11ea-9fe5-9e70520cd8e9.png)

**Additional context**
For whatever it is worth, similar title in this github issue in the past:
https://github.com/appsody/appsody/issues/344

**Comment by kylegc** [comment]
To be clear, we are still handling `Ctrl-c`, and we still intend `Ctrl-c` to kill appsody.

There were some changes in version `0.5.0` to better cleanup when killing an app, and a side-effect of this was a 10 second wait before the container exited.

We were able to reproduce your behavior that `ctrl-c` is not quitting appsody, even after 10 seconds, in the latest version of docker.

**Comment by nastacio** [comment]
> We were able to reproduce your behavior that ctrl-c is not quitting appsody, even after 10 seconds, in the latest version of docker.

I just confirmed that rolling Docker Desktop to 2.1.0.4 makes the problem go away.
