### ISSUE TITLE
appsody stop documentation needs more detail 

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#70]
I was testing the `appsody stop --name` today and I looked at the documentation to see what I needed to list for the name but it didn't help me. Here is what is there currently...
`--name string           Assign a name to your development container. (default "my-project-dev")`
I talked to @kewegner about this and he said currently the best way to get the name is to do a `docker ps` so we should document this or add more verbage as to what to use for the name.

**Comment by neeraj-laad** [comment]
Thanks for spotting this @tnixa.

@kewegner Would you mind updating the docs to make it clearer?

**Comment by kylegc** [comment]
Text was updated, reviewed, and merged.
