### ISSUE TITLE
Need way to pass env to appsody, local and on k8s

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#704]
**Is your feature request related to a problem? Please describe.**

(This request may be related to #373, but I did not see it mention about appsody running in k8s mode.)

Developers need a way to pass env variables to the running appsody application.  Today they can do this via the the `--docker-options` flag and the use of `--env or --env-file` flags (#320)

However, when appsody is running on k8s (i.e. within Eclipse Che w/ Codewind integration), docker options are not applicable.

So we need a common mechanism that works for both local and k8s environments

---

**Describe the solution you'd like**

A way to define environment variables in one location, perhaps in a file that when running locally, would be passed to `docker`; and when running on k8s, would passed to the deployment

(Note: I assume there's some proper way to define the env via some configMap for a production `appsody deploy`, but this issue is about the development deployment side of things)

---

**Describe alternatives you've considered**

An alternative solution I've considered is maybe we just let `--docker-options` be used for local case, and then on k8s, have some way to specify where the same env variables would be defined (perhaps a ref to a configMap?)  This approach may align better with `appsody deploy`

---

**Additional context**

**Comment by nastacio** [comment]
Issue #320

**Comment by chilanti** [comment]
I would say that #320 addresses the local case if there aren't strong objections.
We need to change the K8S path to detect `--docker-options` in `appsody run` and take the appropriate action. Initially, we could just focus on `env`, subsequently we could look at additional `-docker-options` where it makes sense.

**Comment by neeraj-laad** [comment]
As a first pass, we could inspect docker options passed to appsody using `--docker-options` flag and pass them on to k8s deployments.

This will support env flags but not envfile flag for now.

The next stage would be to provide a mechanism to store the environment variables in a config file and use that across both local/k8s scenarios.

**Comment by nastacio** [comment]
I may be missing something, but this is all possible today, though it requires some careful alignment of parameters for `appsody run --docker-options="--env-file ..."` and the app-deploy.yaml file given to kubernetes.

If you have a properties file f.properties with the contents:
```
p1=abc
p2=def
```

Local: Run `appsody run --deploy-options="--env-file f.properties"`
K8s: Before `appsody deploy`:

1. Create a secret with `kubectl create secret generic f-properties-secret --from-env-file=f.properties` 
2. Add the following snippet in app-deploy.yaml

```yaml
spec:
  ...
  env:
  - name: p1
    valueFrom:
      secretKeyRef:
        key: p1
        name: f-properties-secret
  - name: p2
    valueFrom:
      secretKeyRef:
        key: p2
        name: f-properties-secret
```

**Comment by nastacio** [comment]
@neeraj-laad 

> As a first pass, we could inspect docker options passed to appsody using `--docker-options` flag and pass them on to k8s deployments.

I suppose appsody could look into --docker-options, look for environment variables in `-e` and `--env-file` parameters and make the additions to app-deploy.yaml. That said, one would still be left with defining the actual secret object in K8s with that `kubectl create secret generic ...` call.

> This will support env flags but not envfile flag for now.

I have spent considerable time battling/working around this for the past 3 weeks. I would be glad to provide (hopefully useful) feedback on proposed design.
 
> The next stage would be to provide a mechanism to store the environment variables in a config file and use that across both local/k8s scenarios.

See my prior comment. The current "best-practice" (quotes on purpose) I came up with is to always put the properties in file and pass it to `appsody run` with `--docker-options="--env-file ..."` when running locally and map that file to a k8s secret before using `appsody deploy`.

**Comment by makandre** [comment]
@neeraj-laad @nastacio 

From Codewind integration perspective, supporting `--env-file` is preferable to supporting just `--env`.  The use case is then the user can define this env file in their project, and when Codewind sees that it exist, we'd would pass it to appsody via `--docker-options="--env-file"`

**Comment by nastacio** [comment]
@makandre as a developer, I probably don't want the file in the project, lest I mess up and deliver a file full of credentials to git. Case in point, Eclipse proper keeps "run options" in the .metadata folder for the workspace, not inside the projects.

**Comment by makandre** [comment]
I would assume any such file would be git ignored?

**Comment by nastacio** [comment]
> I would assume any such file would be git ignored?

I should, assuming people are paying attention to what they are doing. Additionally, and I think that is the worse part, people often delete and re-clone their project directories, which is yet another reason why run options should not be stored inside the project directory.

**Comment by makandre** [comment]
I think maybe we need to take a step back here.  The original intent of this issue is about passing environment vars to appsody in a way that would work when running locally **and** in k8s.  The most straightforward way to do so (as noted in some of the discussions above) is to have a properties file that can be passed to appsody via `--docker-options` flag, and for that to be taken into effect when running in k8s.

While it's true developers could potentially put credentials into this file and accidentally commit it to their repo, they are doing so at their peril and there are many resources pointing out why this is not a good thing to do.  I should also note we are really talking about dev/test-time environment variables here, as production-time vars (and credentials) would be configured and passed to `appsody deploy` via other means (probably via kube config maps and secrets)

That said, there are also a number of mechanisms out there to configure and secure variables for an application, such as [git-crypt](https://github.com/AGWA/git-crypt), [git-secret](https://git-secret.io/), [ibm-cloud-env](https://www.npmjs.com/package/ibm-cloud-env); just a few that came up in a quick search.  But I'd think maybe is it not the place for appsody CLI or Codewind to lock the developer into any one way of doing things.  In fact, maybe it should be something that's prescribed by the stack owner and therefore built into the stack?  (@neeraj-laad does this make sense?)

**Comment by nastacio** [comment]
Passing environment variables to k8s is achieved via secrets/configMaps in the cluster and mapping the secret data bits into variables through the app-deploy.yaml file.

If appsody will automatically convert files to secrets by wrapping calls to `kubectl create secret ...`, that is a possibility, though it puts the burden on appsody to manage (or at least track) all secrets it would implicitly create during `appsody deploy ...` calls.

About the location of would be environment files, I outlined two different reasons:
1. (less important) the possibility of cluster secrets ending up on git repos
2. (more important) deleting local clone directories and recloning is common practice

Whatever solution involves the ability to pass a file to appsody CLI or codewind has to allow the choice of placement of the file anywhere in the filesystem, which may or may not be inside the git clone for the project. At that point, it is the developer's choice and potential own fault if delivering a file with secrets to source control.
