### ISSUE TITLE
Appsody Build creates multiples images

### ISSUE THREAD

**Issue by dewan-ahmed** [appsody/appsody#712]
**Describe the bug**
An **appsody build** command for nodejs-express stack creates two images instead of one.

**To Reproduce**
1. appsody init nodejs-express
2. <make your application code changes. For example, change a word under app.js file>
3. appsody build -t <someName>:<version>
4. See two images created - one with above name:tag and other without name/tag

**Expected behavior**
Creation of a single image

**Actual behaviour**
Creation of two images - one seems to be the base image (952MB) and the other seems to be the expected slimmed-down image (187MB)

**Environment Details (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser: N/A
 - Version appsody 0.4.9

**If applicable please specify:**
 - CLI version: appsody 0.4.9
 - Stack you are using: nodejs-express

**Screenshots**
root@ubuntu-s-1vcpu-1gb-tor1-01:~/appsody-actions# docker image ls
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
appsody-actions          v1                  b4f84add4876        18 hours ago        187MB
<none>                   <none>              8c1698234012        18 hours ago        952MB

**Additional context**
N/A

**Comment by EnriqueL8** [comment]
Known issue: https://stackoverflow.com/questions/50357285/how-to-delete-image-from-previous-stage-on-docker-multi-stage-build

**Comment by neeraj-laad** [comment]
We could possibly remove dangling images or sue another label to ensure they are appsody images. and then clean up after appsody build. But, it might need stack creators to do some extra work in the multistage Dockerfile.

Also caching can be a benefit for consecutive builds and cleaning anything on user's machine under teh cover seems a bit dangerous.

**Comment by kylegc** [comment]
This is an intended side-effect from Docker for caching. I don't think appsody should be removing these images.

**Comment by chilanti** [comment]
Closing as this is a normal behavior with docker build.
