### ISSUE TITLE
Code coverage analysis for build_delete.go

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#715]
- [ ] newBuildDeleteCmd 
    test build delete runs
    one that passes with no error and one that simulates a build delete error

- [ ] if perr != nil
    test build delete with an invalid project name and verify error

- [ ] if tektonServer == ""
    test build delete with no target Tekton server specified in `~/.appsody/.appsody.yaml` and verify error

**Comment by upLukeWeston** [comment]
The `build delete` command is hidden from users and not used anywhere in the CLI codebase so writing tests wouldn't be worthwhile.
