### ISSUE TITLE
Code coverage analysis for build_setup.go

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#716]
- [ ] func newSetupCmd
test setup command with correct arguments passes with no errors

- [ ] if len(args) < 1
test setup command with no arguments and verify error

- [ ] if tektonServer == ""
test build delete with no target Tekton server specified in `~/.appsody/.appsody.yaml` and verify error

- [ ] if perr != nil
test setup with an invalid project name and verify error

**Comment by upLukeWeston** [comment]
The `build setup` command is hidden from users and not used anywhere in the CLI codebase so writing tests wouldn't be worthwhile.
