### ISSUE TITLE
Appsody config file path seems incorrect in help

### ISSUE THREAD

**Issue by barecode** [appsody/appsody#72]
The output from the CLI states:

$ appsody
The Appsody command-line tool (CLI) enables the rapid development of cloud native applications.

Flags:
      --config string   config file (default is $HOME/.appsody.yaml)

However, the file $HOME/.appsody.yaml does not exist on my system. Rather, the path is `~/.appsody/.appsody.yaml` -- I didn't do anything special when I installed appsody so I assume that's the right path. If so, the documentation and the CLI need to be updated.

**Comment by tomleah** [comment]
Transferred as the CLI generates these docs
