### ISSUE TITLE
Add .templatingignore file for templating in stacks

### ISSUE THREAD

**Issue by CameronMcWilliam** [appsody/appsody#721]
**Is your feature request related to a problem? Please describe.**
The new templating feature applies templating to the tire stack, image + template.  Some read-only files within these stacks, e.g. node modules, can cause a problem especially during local development using `appsody stack package` if they use the same delimiters : `{{` in their code.

**Describe the solution you'd like**
Include a `.templatingignore` file that means templating won't be applied to these files.  It would have the same syntax as a `.gitignore` file.

**Comment by neeraj-laad** [comment]
This is no longer needed as the delimiter used is unique enough to avoid conflicts. We can re-open if we see other situations that need this.
