### ISSUE TITLE
Cannot build app that has capital letters in name

### ISSUE THREAD

**Issue by dokun1** [appsody/appsody#73]
**Describe the bug**
I cannot build an app with `appsody build` if the name of the app has capital letters in it.

**To Reproduce**
I've generated a Kitura Swift app using the Kitura CLI with these steps:

```bash
mkdir RazeKube
cd RazeKube
kitura init
```

After that, I run `appsody init swift --no-template` and the project is configured. I then want to run `appsody build`

**Expected behavior**
The docker container should build, allowing me to run `appsody run`

**Actual behavior**
```bash
➜ appsody build
Extracting project from development environment
Running command: docker[pull appsody/swift:0.1]
Running command: docker[create --name RazeKube-extract -v /Users/davidokunibm/RayWenderlich/rw-cloud-native/final/RazeKube/:/project/user-app appsody/swift:0.1]
Running command: docker[cp RazeKube-extract:/project /Users/davidokunibm/.appsody/extract/RazeKube]
Running command: docker[rm RazeKube-extract -f]
Project extracted to /Users/davidokunibm/.appsody/extract/RazeKube
Running command: docker[build -t RazeKube -f /Users/davidokunibm/.appsody/extract/RazeKube/Dockerfile /Users/davidokunibm/.appsody/extract/RazeKube]
[Error] Error running docker command: exit status 125
```

**Environment Details (please complete the following information):**
- OS: macOS
- Xcode: 10.2
- Docker: 18.09.2

**If applicable please specify:**
 - CLI version: 0.2.2
 - Stack you are using: macOS

**Additional context**
I would think about adding a `toLower()` function for the naming of these Docker containers.

**Comment by seabaylea** [comment]
This occurs because Docker doesn't allow capitals in image tags - not that it doesn't affect run, test, etc as Docker is fine with having capitals in container names ;-)

**Comment by chilanti** [comment]
We'll do two things:
1) Lowercase the name of the docker image to build
2) Add a -t <tag> option to allow the end user to pick a name and a tag

**Comment by chilanti** [comment]
This was addressed in https://github.com/appsody/appsody/pull/75, which was merged today.

**Comment by tomleah** [comment]
This will land in `0.2.5`, estimated 24th July 2019.
