### ISSUE TITLE
Code coverage analysis for init.go

### ISSUE THREAD

**Issue by CameronMcWilliam** [appsody/appsody#737]
- [x] if !valid after valid, err := IsValidProjectName(config.projectName)
       initAppsody -  test IsValidProjectName with an invalid project name
- [ ] if err != nil after repos.getRepos
       initAppsody -  test repos.getRepos with an invalid RootCommandConfig
- [x] if err != nil after repos.GetIndices
       initAppsody -  test repos.GetIndices with an invalid logging config
- [x] if len(indices) == 0 after repos.GetIndices
       initAppsody -  test repos.GetIndices with 0 indices
- [ ] if strings.Compare(index.APIVersion, supportedIndexAPIVersion) == 1
       initAppsody -  test with an unsupported index API version
- [ ] if len(index.Projects[projectType]) >= 1
       initAppsody
- [x] if template == "" in for indexNo, stack := range index.stacks
        initAppsody  - test with empty template name
- [x] if projectName == "" && inputTemplateName != "none"
      initAppsody - test with empty project name and non-empty inputTemplateName
- [x] if err == nil after _, err = os.Stat(appsodyConfigFile)
        initAppsody - test running appsody init on an existing project
- [ ] (if v != "" after for _, v := range reqsMap) & (!mapEmpty)
       initAppsody - test with a non empty map of requirements
- [ ] if err != nil after downloadFileToDisk
       initAppsody  - test with an invalid projectName and a valid fileName
       initAppsody  - test with a valid projectName and an invalid fileName
      initAppsody -  test with an invalid projectName and an invalid fileName
- [x] if config.Dryrun
        test initAppsody in dry run mode
- [ ] if errUntar != nil
       test initAppsody on a non-empty stack directory
- [ ] if dryrun in untar
       test dry run untar 
- [ ] if err != nil in isFileLayDownSafe after ioutil.ReadDir(directory)
       test isFileLayDownSafe on an invalid directory
- [ ] if err != nil in preCheckTar after os.Open(file)
      test preCheckTar on invalid file path
- [ ] if !fileInfo.IsDir() 
       test with a header name that exists in the file system and the template project
- [ ] if !preCheckOK should happen from above test
- [ ] extractAndInitialize with a Buildah command config
      test with dry run enabled
- [ ] extractAndInitialize with a Buildah command config
      test without dry run enabled
- [ ] extractAndInitialize with a Buildah command config
      test without a script present
      test with a script present 
- [x] if len(parms[0]) == 0 || len(parms[1]) == 0 in parseProjectParm 
        test parseProjectParm with slash at beginning or end of project parameter
- [x] if len(parms) > 2
        test parseProjectParm with more than 2 slashes in project parameter

**Comment by upLukeWeston** [comment]
In `init_test.go` there are a few instances of `_, _` - could you change those to have `err, _` and proper validation while you're changing this file anyway :)
