### ISSUE TITLE
Code coverage analysis for operator_utils.go

### ISSUE THREAD

**Issue by Kamran64** [appsody/appsody#742]
Since Travis doesn't currently support kubectl, the following functions can't be tested yet: `RunKubeExec`, `RunKubeGet`, `RunKubeDelete`, and `RunKube`.

`func operatorExistsInNamespace(log *LoggingConfig, operatorNamespace string, dryrun bool) (bool, error)`
- [ ] Run function when operator already exists in namespace and verify message
- [ ] `if getOutput == "" `
    Run function when getOutput == "" and verify message is "There are no deployments with the appsody-operator".
- [ ] Run function when getOutput has value and check message above is not outputted.

`func operatorExistsWithWatchspace(log *LoggingConfig, watchNamespace string, dryrun bool) (bool, string, error)`
- [ ] if watchNamespace == "" && getNamespacesOutput != ""
    Check this codepath and verify output string and returned error.

- [ ] if podWatchSpace == "" {
    Pass in empty value for podWatchSpace and verify result

`func getOperatorWatchspace(log *LoggingConfig, namespace string, dryrun bool) (string, error)`
- [ ] if !operatorExists
    Run function with no existing operator

`func getWatchSpaces(csvList string, dryrun bool) []string`
- [ ] `if csvList == "" {`
    Verify nil is returned after passing in an empty string for `csvList`

**Comment by upLukeWeston** [comment]
It isn't currently possible to create tests for `operator_utils.go` due to the use of Kube commands being invoked by the functions.
