### ISSUE TITLE
Code coverage analysis for stack_validate_utils.go

### ISSUE THREAD

**Issue by CameronMcWilliam** [appsody/appsody#748]
- [ ] Test RunAppsodyCmdExec 
- [ ] Test RunDockerCmdExec
- [ ] if runtime.GOOS == "windows" in AddLocalFileToRepo
       Test AddLocalFileToRepo on Windows

**Comment by Kamran64** [comment]
These functions will be tested as a result of running appsody stack validate in the tests from https://github.com/appsody/appsody/issues/747. Closing.
