### ISSUE TITLE
Auto-generated CLI markdown for Appsody.dev contains invalid HTML

### ISSUE THREAD

**Issue by KyeMaloy97** [appsody/appsody#761]
**Describe the bug**
When the CLI commands are stripped and converted to a markdown file, the <variable names> are left as are, with their angled brackets. 

Ones inside code blocks are escaped in Markdown but whenever one is used in a paragraph, it is not rendered currently. The glossary page PR (https://github.com/appsody/website/pull/442/) also adds MDX support to the site, and these variable names are treated as HTML tags and because there is no </> tag, the rendering fails and the page is not available to view (loads blank).

There are a few ways to address this, from modifying the `docs.go` file that runs to do something about the brackets at the same time as it sorts out links. We could also make a script that sorts it out that runs after the MD is generated but before the Travis PR is opened. Or we can just change from using <> to something else, like |this| or {this} or _this_. 

Changing the characters used may involve changing the actual CLI command help text, which would show up on the Terminal, which might not be great. Escaping the brackets with backticks would be a solution that would fix the website but result in the CLI getting backticks showing in prompt when running help. This might break or make the codeblocks on the website look strange though, as they escape everything inside so they would render the actual backticks, for example the image below would have the code block showing <name> surrounded with ticks.

**To Reproduce**
1. Go to Appsody.dev
2. Scroll to appsody stack create
3. Look in synopsis, where it says `a new Appsody stack called ,`, the name is cut off.

**Expected behavior**
Variable names inside text to render

**Actual behaviour**
They are not rendered.

**Screenshots**
![Screenshot 2019-12-04 at 15 53 26](https://user-images.githubusercontent.com/24469095/70158011-6ef6a580-16ae-11ea-99b1-9fb67a7f40c6.png)

**Comment by kylegc** [comment]
Good find. Since it appears that the cli in generating invalid markdown, I think the cli should fix it.

What is needed is a single escape character before the opening `<` like this `\<`. That will fix the markdown anyway. @KyeMaloy97 will you test that the website handles this escape if we implement it in the cli markdown?

@kewegner how hard would it be to create a regular expression to find all these instances and add an escape? Note we don't want the escape when inside backticks.

**Comment by KyeMaloy97** [comment]
@kylegc Can confirm that if the markdown puts a \ in front of the first angled bracket, the content is rendered correctly.

Just need to make sure it doesn't do the fix inside code blocks, as then the escaping \ will be escaped and show in the code blocks. I will guess it will need to be an interim step before opening the Travis PR into the website to add the new `CLI-commands.md` file? So the website gets the changes but the Terminal doesn't.

### Rendered Content
![Screenshot 2019-12-11 at 10 11 31](https://user-images.githubusercontent.com/24469095/70612318-9d203c00-1bfe-11ea-9fa7-a1569cc11b08.png)

### Code change
![Screenshot 2019-12-11 at 10 11 48](https://user-images.githubusercontent.com/24469095/70612342-a7423a80-1bfe-11ea-95ff-9d73fbb8a4c4.png)

**Comment by kylegc** [comment]
Yes, this was fixed when the CLI generates the markdown file. It was released yesterday and the website looks good now.

Thanks for finding this! If you see any other problems like this, please let us know.
