### ISSUE TITLE
Cannot inspect index.docker.io/appsody/<image>

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#762]
**Describe the bug**

I believe this is a regression introduced in `0.5.1` and higher.  When running in k8s environment, we are getting this error:

```
[Error] Could not inspect the image: exit status 1: error reading build object "index.docker.io/appsody/nodejs-express:0.2": error reading image: error locating image "index.docker.io/appsody/nodejs-express:0.2" for importing settings: error locating image with name "index.docker.io/appsody/nodejs-express:0.2" ([localhost/index.docker.io/appsody/nodejs-express:0.2 registry.redhat.io/index.docker.io/appsody/nodejs-express:0.2 quay.io/index.docker.io/appsody/nodejs-express:0.2 docker.io/index.docker.io/appsody/nodejs-express:0.2]): image not known
```

The image name should not have `index.` prefixed

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version: 0.5.2
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by chilanti** [comment]
Looking into it. Question - did you try a fresh installation of Appsody? Or is it possible that `.appsody.yaml` had been left over from prior installations? We do not reference `index.docker.io` anylonger in 0.5.1 and higher. But this is still a problem - because we ought to handle that `index.docker.io` situation, and map it to `docker.io` (as it was done for `buildah pull` - in your logs).

**Comment by makandre** [comment]
We found the root cause... it is because we bundle an `.appsody.yaml` and that wasn't updated.  We'll fix it on our side.  Sorry for the scare!

**Comment by chilanti** [comment]
So - there's still a problem which we'll fix in the next release - but yes, if you update the `.appsody.yaml`, the problem isn't apparent any longer. So - let's go with that. I'll create another issue to address the case where someone may still have `index.docker.io` lingering around.
