### ISSUE TITLE
appsody deploy misses external ip discovery for IBM Cloud deployment

### ISSUE THREAD

**Issue by richard-trotter** [appsody/appsody#764]
When I run appsody (0.5.2) deploy to deploy to my IBM Cloud K8s cluster, appsody fails to discover the node external-ip for my NodePort service. Note missing host part of the reported url:

> Deployed project running at http://:31241

The expected external ip is:
> $ kubectl  get nodes -o wide | awk '{print $7}'
> EXTERNAL-IP 
> 173.193.82.18

**Comment by kylegc** [comment]
Thanks, we'll take a look.

**Comment by EnriqueL8** [comment]
I also encountered the same issue when running it on minishift locally

**Comment by nastacio** [comment]
Another user hitting the issue. It is interesting to note how the resolution may be out of reach for people without relatively deep Kubernetes skills:

https://appsody.slack.com/archives/CKXDDB4A3/p1579189104014200

**Comment by neeraj-laad** [comment]
Another instance related to this -  https://github.ibm.com/experiential-squads/ibm-cloud-connect/issues/15 

Not sure if this is deploying to IBM cloud though.

**Comment by nastacio** [comment]
I can confirm it works now, thanks!
