### ISSUE TITLE
appsody run fails with Docker Toolbox

### ISSUE THREAD

**Issue by MaruthiKomera** [appsody/appsody#775]
**Describe the bug**

**To Reproduce**
```
E:\maruthi\IBM-meetup\mk\quote-frontend>appsody run
Running development environment...
Pulling docker image docker.io/appsody/nodejs-express:0.2
Running command: docker pull docker.io/appsody/nodejs-express:0.2
0.2: Pulling from appsody/nodejs-express
Digest: sha256:1ef7e63b1480494ffae54e95164e386385b84d580fa8fe84d9f024abd787697c
Status: Image is up to date for appsody/nodejs-express:0.2
docker.io/appsody/nodejs-express:0.2
Running command: docker run --rm -p 3000:3000 -p 9229:9229 --name quote-frontend-dev -v E:/maruthi/IBM-meetup/mk/quote-frontend/:/project/user-app -v quote-frontend-deps:/project/user-app/node_modules -v appsody-controller-0.3.2:/.appsody -t --entrypoint /.appsody/appsody-controller docker.io/appsody/nodejs-express:0.2 --mode=run
[Container] docker: Error response from daemon: invalid mode: /project/user-app.
[Container] See 'docker run --help'.
[Error] Error in 'appsody run': exit status 125
```

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Windos 8

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

thanks. I can run any debug steps you may suggest' it is reproducible easi;y/

**Comment by tnixa** [comment]
Can you try this on Windows 10? We don't support Windows 8. Can you try it in verbose mode `appsody run -v` ?

**Comment by neeraj-laad** [comment]
Closing this issue as we do not support Windows 8. Please try this on a supported platform and re-open if this is still an issue.
