### ISSUE TITLE
Is it possible to provide Appsody binary download for "ppc64le" architecture?

### ISSUE THREAD

**Issue by vrushaliinamdar** [appsody/appsody#781]
Hi Team,

We have recently built "appsody" binary from source on linux/ppc64le architecture. We found that ppc64le specific binary is not available for download under https://github.com/appsody/appsody/releases.

Is it possible to make it available for download. We have built it from source by using following steps:

- Create following directory structure to build go based packages.
$HOME/go/bin/src/github.com/appsody/Pkg
-  Clone appsody source code into appsody directory from https://github.com/appsody/appsody.
- Install ‘go’ using steps mentioned at https://tecadmin.net/install-go-on-centos.
- Go into $HOME/go/src/github.com/appsody/appsody directory.
- Execute `go build` command to build appsody executable.
- copy both the binaries into /usr/bin directory.
- Execute `appsody version` command to verify the binary.

Please let me know the feasibility.

Regards,
Vrushali

**Comment by kylegc** [comment]
Yes this should be doable. We'll let you know when a prototype is available to test because I don't think we have any ppc machines available to test on.

**Comment by vrushaliinamdar** [comment]
Sure, we can test. Thank you.

**Comment by kylegc** [comment]
We added this to our build process and just released 0.5.3

Please try this out: https://github.com/appsody/appsody/releases/download/0.5.3/appsody-0.5.3-linux-ppc64le.tar.gz

**Comment by vrushaliinamdar** [comment]
Sure.

**Comment by vrushaliinamdar** [comment]
@kylegc I could download the tar file and "appsody version" command worked properly on ppc64le system.
Thanks a ton for your support !
