### ISSUE TITLE
Appsody CLI doesn't seem to handle --env-file <file name> correctly in certain cases

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#820]
**Describe the bug**
In certain situations, `appsody run .... --docker-options "--env-file myfile"` will not propagage `myfile` to the `docker command`

**To Reproduce**
Asking the Codewind team for details on how to reproduce this.

**Comment by chilanti** [comment]
Can't reproduce the behavior.
When I run:
```
appsody run --docker-options "--env-file /Users/mchilant/dockertest.env"
```
I correctly obtain the following `docker` invocation:
```
docker run --rm -p 5678:5678 -p 8080:8080 --name test-python-dev -v /Users/mchilant/test-python/:/project/userapp -v test-python-deps:/project/deps -v appsody-controller-latest:/.appsody --env-file /Users/mchilant/dockertest.env -t --entrypoint /.appsody/appsody-controller docker.io/appsody/python-flask:0.1 --mode=run
```

**Comment by makandre** [comment]
I think I know what happened.  We call `appsody` via a wrapper script, that is somehow messing up the quoting.

So yes, on local, calling `appsody` CLI directly with `--env-file file` works.

But, on k8s, again calling `appsody` CLI directly with `--env-file file` now gives:

```
panic: runtime error: slice bounds out of range [11:10]
goroutine 1 [running]:
github.com/appsody/appsody/cmd.ExtractDockerEnvVars(0x7ffc2683d393, 0xa, 0xc0000e4510, 0xc00043a06d, 0x1e)
	/Users/andrewmak/go/src/github.com/appsody/appsody/cmd/utils.go:137 +0x556
```

**Comment by chilanti** [comment]
Looking at the code, it seems that the script gives us a string for `dockerOptions` that ends right after `--env-file` (hence the panic, which I am fixing - but this fix won't resolve the underlying problem with the script).

**Comment by chilanti** [comment]
@makandre - I am closing this one since it seems that the problem is more on the calling script than in appsody - feel free to re-open if relevant.
