### ISSUE TITLE
Appsody stack create should create stack based on 

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#832]
`appsody stack create` copies the `samples/sample-stack`

This stack is not working so user's can not run other appsody stack commands using that stack. It might be worth :

- switching this command to use `incubator/starter` stack.
- update docs  / cli help text to reflect this change

We might want to keep the old samples folder for now.. After a couple of releases, we can delete it.

**Comment by CameronMcWilliam** [comment]
Added in with #833
