### ISSUE TITLE
Stack create name length constraint documentation is incorrect 

### ISSUE THREAD

**Issue by mezarin** [appsody/appsody#848]
The following command shows:
$ appsody stack create abcdefghij-abcdefghij-abcdefghij-abcdefghij-abcdefghij-abcdefghij-c69
[Error] Invalid project-name "abcdefghij-abcdefghij-abcdefghij-abcdefghij-abcdefghij-abcdefghij-c69". **The name must be 68 characters or less**

The documentation here: https://appsody.dev/docs/using-appsody/cli-commands#appsody-stack-create shows:

The stack name must start with a lowercase letter, and can contain only lowercase letters, numbers, or dashes, and cannot end with a dash. **The stack name cannot exceed 128 characters.**

**Comment by CameronMcWilliam** [comment]
Included as part of the #856 PR
