### ISSUE TITLE
Define strategy for testing infrastructure on multiple platforms

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#85]
This issue is intended to create a strategy for short term and long term testing of appsody on all supported platforms. Ideally we would have a full automated test suite that runs on every PR. However this isn't possible today because Travis CI doesn't support running docker linux containers on all the platforms we need (see #41 ). Also, our automated test suite isn't fully developed yet (see #44 ).

## Platforms we need to test
- MacOS
- Debian/Ubuntu linux
- Red Hat linux
- Windows 10

Today the only one we can test fully automated with Travis is Ubuntu linux.
Other platforms are manually tested.

## Todos for this issue
- Determine if there are other CI systems we can use (such as AppVeyor for windows  appveyor/ci#1717)
- Determine if we can get other test infrastructure on a cloud and how and when we would run the tests there
- Determine what platforms cannot be tested on a cloud and how we will handle testing for these platforms

**Comment by neeraj-laad** [comment]
Closing this for now. We can re-open when we feel need to make significant changes in this area.
