### ISSUE TITLE
`appsody deploy` command deploys with the wrong image version

### ISSUE THREAD

**Issue by brightzheng100** [appsody/appsody#858]
**Describe the bug**

```
$ appsody deploy --no-build -t registry:5000/spring-boot-demo:v0.1.0 --namespace default

$ kubectl get appsodyapplication
NAME               IMAGE                                   EXPOSED   RECONCILED   AGE
spring-boot-demo   registry:5000/spring-boot-demo:v0.1.1   true      True         8s
```

As you can see, the image version deployed uses the one in `app-deploy.yaml`, which is `v0.1.1`, instead of the one, which is `v0.1.0` instructed by the command line.

**Expected behavior**

`appsody build` may generate the `app-deploy.yaml` but once the values have been specified in `appsody deploy`, the command line should follow exactly the instructions to deploy -- whether the command should update the `app-deploy.yaml` might be another question (and I prefer to update accordingly).

**Actual behaviour**
What is the actual behaviour.

If simply deploying by following the existing `app-deploy.yaml`, what's the point to specify `-t` in `appsody deploy`?

**Environment Details (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**If applicable please specify:**
 - CLI version:

```
$ appsody version
appsody 0.5.3
```

 - Stack you are using:

```
java-spring-boot2	0.3.18   	*default
```

**Comment by EnriqueL8** [comment]
I believe this is more an issue of verifying which flags can be used with the `--no-build` flag. Discussion: https://appsody.slack.com/archives/CKQ9R1X6V/p1579691499009700

The ideal flow would be:
- `appsody build -t my-ns/my-image` and this will generate an `app-deploy.yaml` where the `applicationImage` field is set to `my-ns/my-image`.
- `appsody deploy --no-build` will just do a `kubectl apply -f app-deploy.yaml`

It only makes sense to add a tag when appsody is building an image, and thus modify the `app-deploy.yaml`. This deployment manifest should be describing how to deploy this microservice, which is stored in the built image.

**Comment by neeraj-laad** [comment]
I believe this is working as designed. I'm closing this issue, please raise a separate issue if you believe the implementation can be made clearer and suggest some alternatives.
