### ISSUE TITLE
Add image information to Index.yaml

### ISSUE THREAD

**Issue by kilnerm** [appsody/appsody#868]
**Is your feature request related to a problem? Please describe.**

Presently the only way to see what image a particular stack in my index will use is to look in the `.appsody-config.yaml` from either creating an application for the stack or extracting the template zip and relies on an understanding of how the stacks are put together.

Further, if we implement the function as described in #867 then having the image tag clearly accessible will help developers understand what patching behaviour they would get (we could even enhance `appsody list` to display this).

**Describe the solution you'd like**

I would like the image tag meta-data added to the `.apsody-config.yaml` to be duplicated in the generated index files for ease of reference.

**Describe alternatives you've considered**

Extracting the templates zip or creating an application to extract the information. Both these actions are processing-intensive and will not scale well for large volumes of stacks.

**Additional context**
This will be very useful for the current Kabanero implementation.

**Comment by neeraj-laad** [comment]
I am wondering if the index should just list out the full image tag and digest information that is built as part of appsody stack package. 

stack:
  image: 
    tag: reg/name/version
    digest: <image digest>

This way the index becones a single place for understanding what was built (src), where it was published (docker image, src url, templates url).

**Comment by Kamran64** [comment]
I have the fully qualified image tag in the index now but I'm struggling to get the digest. I think an image digest is only generated if you push or pull to/from a registry hence why I'm seeing `<none>` for my digest values after building locally. See: https://github.com/moby/moby/issues/32016 and [here](https://stackoverflow.com/questions/44087012/sha256-of-locally-built-docker-image).

@kilnerm - Would it be okay to only have the image tag?

**Comment by kilnerm** [comment]
@Kamran64 Yes, looking at the digest situation I don't think it is reasonable to add that in the context of our current tooling.
