### ISSUE TITLE
Appsody forces add of image-registry to stack definition in template

### ISSUE THREAD

**Issue by groeges** [appsody/appsody#871]
**Describe the bug**
Latest Appsody CLI adds a default image registry value to the .appsody-configf.yaml file from the template when init-ing a project. This causes incompatibilities with Kabanero and ICPA products which validate that the value in the projects .appsody-config.yaml matches the value that was configured when Kabanero stacks were created in OpenShift.  Earlier version of the CLI didn't do this, nor did the earlier stack build processes add this image registry to the templates.
 
**To Reproduce**

**Expected behavior**
Expected projecy .appsody-config.yaml to match what is obtained from the template.

**Actual behaviour**
Image registry value gets added to the stack element in .appsody-config.yaml

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:  0.5.6
 - Stack you are using:   any from https://github.com/kabanero-io/collections/releases/download/0.4.0/kabanero-index.yaml

**Screenshots**

**Additional context**

**Comment by kylegc** [comment]
Fixed by https://github.com/appsody/appsody/pull/874
