### ISSUE TITLE
Refactor code to use a common project name function

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#88]
In PR https://github.com/appsody/appsody/pull/75
we made the default build name all lower case. However, there are many places around the CLI code that calculate the default project name which were not affected.

This issue is to create a common getProjectName() util function, then update all the rest of the CLI to use it. The new method should return all lowercase letters.

**Comment by chilanti** [comment]
The common function is there. It needs to be adopted through the CLI (currently, it's only being used once).
