### ISSUE TITLE
Stack Package Git Labels

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody#881]
**Describe the bug**
2 Issues:
 - 1) The travis builds for the appsody stacks repo runs a `stack package` command for the release. This command adds a series of labels to the built image, where some labels contain git information. Due to the setup of a Travis build, when the git repo is cloned into the machine and a new branch is checked out. Since this branch does not have an upstream, we are unable to construct all the labels for the image (url for the source).
 
- 2) This git information is added to the image as opencontainers labels:
```
org.opencontainers.image.url
org.opencontainers.image.documentation
org.opencontainers.image.source
org.opencontainers.image.revision
```
Currently the urls point to the remote branch: `https://github.com/appsody/stacks/tree/master/incubator` but this is not very accurate because that branch could be updated after this image is built. Instead the full url should be pointing to the specific commit used at the time the image was built.
This is also true in the local case where a user has created more commit to a local branch, but hasn't pushed them to the remote.

**To Reproduce**
1. Go to a Travis build for a stack and look at the logs
2. You should see the way travis clones the stacks repository and the warning message for the labels

**Expected behavior**
We expect the travis buiild to add the correct labels to the published images for the stacks, and for these labels to be pointing to a specific code change (not a branch).

**Environment Details:**
 - OS: Travis/MacOs
 - CLI version: 0.5.6
 - Stack you are using:

**Comment by CameronMcWilliam** [comment]
Will look further into this after a team discussion

**Comment by EnriqueL8** [comment]
PR merged for updating Travis.
