### ISSUE TITLE
Stack registry errors on every command

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody#882]
**Describe the bug**
When running an appsody command with verbose, the new stack registry path looks for the stack registry in the config file. This fails if the current directory is not an appsody project, for example during a `stack package` command. See:

![image](https://user-images.githubusercontent.com/30461857/73848678-79edc380-4820-11ea-9dac-c5f1b1536b4e.png)

**To Reproduce**
1. Go to an empty directory
2. Run `appsody -v`
3. See error

**Expected behavior**
This messages should not show up on commands that do not need this check. We should only run this check on init, run, debug...

**If applicable please specify:**
 - CLI version: 0.5.8

**Comment by kylegc** [comment]
This is happening while cobra is initializing the command flag, before we even know which command is being run.
