### ISSUE TITLE
appsody extract doesn't work when using Minikube docker daemon

### ISSUE THREAD

**Issue by matthewpwilson** [appsody/appsody#885]
**Describe the bug**
I run a local Minikube cluster on my workstation. I normally build images using the docker daemon in Minikube. However, when I use `appsody extract` with the Minikube docker daemon, `appsody extract` fails to actually extract my application - I just get the stack.  This causes `appsody deploy` to fail as well. 

**To Reproduce**
1. Connect to minikube docker daemon
```
eval $(minikube docker-env)
```
2. 
```
appsody init java-openliberty
```
3. 
```
appsody extract
```
4. 
```
ls -al /home/mattwil/.appsody/extract/appsody-extract-issue/user-app
total 8
drwxr-xr-x. 2 mattwil mattwil 4096 Feb  6 15:09 .
drwxr-xr-x. 6 mattwil mattwil 4096 Feb  6 09:50 ..
```

**Expected behavior**
My application should be copied to the extract directory under user-app.

At a minimum, if this Minikube scenario is not deemed supported, it would be useful to document this, and give an error when I try to do it.
**Actual behaviour**
What is the actual behaviour.
The user app doesn't get copied, just the stack with an empty user-app directory. 

I think what happens is that because Minikube runs in a VM, when appsody does 
`docker create`, the docker daemon in MInikube will try to bind the project directory (due to `-v /home/mattwil/Documents/Events/appsody-extract-issue/.:/project/user-app`) from the VM, rather than the host filesystem.
Of course the app isn't there, so it doesn't end up in the image.  I'm surprised the `docker create` doesn't actually fail. 
I verified this by doing a `docker run` with the same arguments as the `docker create`, and then checked `/project/uesr-app`, which was empty. 
 

Complete output:
```
Extracting project from development environment
Pulling docker image docker.io/appsody/java-openliberty:0.1
Running command: docker pull docker.io/appsody/java-openliberty:0.1
0.1: Pulling from appsody/java-openliberty
Digest: sha256:5da7b29d1ef6806a76965cec7086d570dbca929ec9ea58270fbc4eb7b21c8a71
Status: Image is up to date for appsody/java-openliberty:0.1
docker.io/appsody/java-openliberty:0.1
[Warning] The stack image does not contain APPSODY_PROJECT_DIR. Using /project
Running command: docker create --name appsody-extract-issue-extract -v /home/mattwil/.m2/repository:/mvn/repository -v /home/mattwil/Documents/Events/appsody-extract-issue/.:/project/user-app docker.io/appsody/java-openliberty:0.1
Running command: docker cp appsody-extract-issue-extract:/project /home/mattwil/.appsody/extract/appsody-extract-issue
Project extracted to /home/mattwil/.appsody/extract/appsody-extract-issue
Running command: docker rm appsody-extract-issue-extract -f
```
**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] RHEL 7.7

**If applicable please specify:**
 - CLI version: 0.5.6
 - Stack you are using: java-openliberty 

**Screenshots**

**Additional context**
If you try to `apposdy deploy` when connected to the Minikube docker daemon, it fails like this:
```
[Docker] Step 10/33 : COPY ./user-app/pom.xml /project/user-app/pom.xml
[Docker] COPY failed: stat /var/lib/docker/tmp/docker-builder806952997/user-app/pom.xml: no such file or directory
[Error] exit status 1
```
due to the missing files from `appsody extract`.

It's possible to work around this issue by pointing at the local Docker daemon (rather than the minikube one) and using `appsody deploy --push`.

**Comment by neeraj-laad** [comment]
@CameronMcWilliam Can you please try to reproduce this?

**Comment by CameronMcWilliam** [comment]
We have no support for using daemons other than the local Docker Daemon in Appsody currently.  Contributors are welcome to look into this issue if they wish.

**Comment by matthewpwilson** [comment]
Fair enough. I think it would be worth calling this out explicitly in the documentation though wrt Minikube. as it took me a long time to figure why it wasn't working and how to work around it.

**Comment by neeraj-laad** [comment]
@helenmasters Can we doc this somewhere on the website as suggested?

**Comment by skoh7645** [comment]
discussed with @helenmasters and decided to doc this workaround in the FAQ and link this in the deploy doc

**Comment by neeraj-laad** [comment]
docs updated
