### ISSUE TITLE
Bug: Appsody documentation out of date for deploying through Tekton pipelines

### ISSUE THREAD

**Issue by atrieder** [appsody/appsody#887]
**Describe the bug**
The Appsody documentation linked [here](https://appsody.dev/docs/using-appsody/building-and-deploying/#deploying-your-app-through-a-tekton-pipeline) directs users to run `appsody deploy --generate-only`, but this causes a `namespace` field to be set to `default` in the 'app-deploy.yaml' file. If included in a Tekton pipelineRun, the deployment will fail.

It looks like the solution might be to replace `appsody deploy --generate-only` with `appsody build` in the documentation.

**To Reproduce**
1. Go to [https://appsody.dev/docs/using-appsody/building-and-deploying/#deploying-your-app-through-a-tekton-pipeline](https://appsody.dev/docs/using-appsody/building-and-deploying/#deploying-your-app-through-a-tekton-pipeline) to see the relevant documentation.
2. Follow the steps in the section linked in the previous step.
3. After running `appsody deploy --generate-only`, verify that a `namespace` field exists in the generated 'app-deploy.yaml' file.

**Expected behavior**
The default namespace should not have been specified in the file, as a different namespace can be used by the Tekton pipelineRun.

**Actual behaviour**
The namespace specified in the file is used instead of the namespace of the Tekton pipelineRun, preventing successful deployment.

**Environment Details (please complete the following information):**
 - OS: Ubuntu 18.04 (virtual machine with Appsody) / Mac OS X Catalina (host with web browser)
 - Browser: Microsoft Edge (host)
 - Version: 81.0.389.2

**If applicable please specify:**
 - CLI version: 0.5.5
 - Stack you are using: NodeJS Express (sample app)

**Screenshots**
![Screen Shot 2020-02-04 at 1 58 12 PM](https://user-images.githubusercontent.com/21695410/73974937-efbe6180-48ea-11ea-9a3e-4e015dabde1f.png)

**Additional context**

**Comment by helenmasters** [comment]
@atrieder thanks for raising this - you were right on all counts! I've raised a PR to fix this on the website https://github.com/appsody/website/pull/515. Enrique has also updated the example.

**Comment by helenmasters** [comment]
Closing this issue as the PR on the website has now been merged. Andrew, please reopen this issue or raise another issue if you find any other problems!
