### ISSUE TITLE
Let APPSODY_MOUNT_HOME to override with named docker volume

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#895]
**Is your feature request related to a problem? Please describe.**

I recall that appsody exposed the `APPSODY_MOUNT_HOME` env variable for Codewind to use, primarily for mounting the local system's m2 cache when running `appsody` inside of Codewind's container. 

However, Codewind currently no longer does this, as it was deemed that mounting the m2 cache is inherently unsafe (there are some details in this [issue](https://github.com/eclipse/codewind/issues/583))

This means for stacks that require m2 cache, when used in Codewind there's no caching of dependencies at all (since such stacks typically don't set `APPSODY_DEPS` either).  This leads to 2 problems:

1. Dependencies need to be downloaded each time the application starts (https://github.com/eclipse/codewind/issues/583) 
2. Users will have problems working on projects based on these stacks in air-gap/offline scenarios

**Describe the solution you'd like**

Would like to repurpose/enhance the `APPSODY_MOUNT_HOME` mechanism so we can use it to specify a named docker volume to cache the dependencies

**Describe alternatives you've considered**

**Additional context**

**Comment by makandre** [comment]
I open https://github.com/appsody/appsody/pull/896 with a proposed solution

**Comment by neeraj-laad** [comment]
@makandre Thanks for the Issue and submitting the PR.. :)

In Appsody we have 2 sets of stacks:

- stacks that use volume for caching dependencies via APPSODY_DEPS (preferred)
- stacks that use bind mount for sharing dependencies with the host (~/.m2)

If I understand this correctly, your solution addresses the second scenario. Do we do something similar already for the first?

**Comment by makandre** [comment]
Hi @neeraj-laad, for stacks using `APPSODY_DEPS`, it already works in offline scenarios I tested; the dependencies would be downloaded to the docker volume initially while the user still had an Internet connection.  Then, when they need to work offline, the docker volume will contain what they need to get some work done.

My solution essentially makes stacks using `~/.m2` mounting behave like the first scenario in Codewind.

**Comment by makandre** [comment]
https://github.com/appsody/appsody/pull/896 was merged and tested in master branch.  Closing.
