### ISSUE TITLE
Couldn't remove the stacks from repo "dev.local"

### ISSUE THREAD

**Issue by brightzheng100** [appsody/appsody#897]
**Describe the bug**
During the development of Apposody Stack, I found that I **couldn't delete the Stacks** that are under `dev.local` repo, which is the default repo if nothing is specified while issuing `appsody stack package`.

**To Reproduce**

```
$ appsody repo list
NAME      	URL
*dev.local	file:///Users/brightzheng/.appsody/stacks/dev.local/dev.local-index.yaml

$ appsody list dev.local
REPO     	ID                    	VERSION  	TEMPLATES	DESCRIPTION
dev.local	springboot-swagger-jpa	0.1.0    	*default 	A Stack managed by Maven, with Spring Boot, Swagger, JPA

$ appsody stack remove-from-repo "dev.local" springboot-swagger-jpa
******************************************
Running appsody stack remove-from-repo
******************************************
Repository index file not found - unable to remove stack
```

**Expected behavior**
Once issued `appsody stack remove-from-repo <REPO> <STACK>`, the Stack should be removed from repo accordingly.

**Actual behaviour**
Error occurred: 

```
Repository index file not found - unable to remove stack
```

**Environment Details (please complete the following information):**
 - OS: Mac

**If applicable please specify:**
 - CLI version: appsody 0.5.6
 - Stack you are using: A new stack that I'm developing but it applies to any Stack under `dev.local` repo.

**Comment by CameronMcWilliam** [comment]
Closed with #904
