### ISSUE TITLE
Error while using appsody on PPC64LE

### ISSUE THREAD

**Issue by vrushaliinamdar** [appsody/appsody#899]
I am getting following error while validating the java-spring-boot2 appsody stack:
```
[Container] docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/.appsody/appsody-controller\": stat /.appsody/appsody-controller: no such file or directory": unknown.
[Error] Error in 'appsody test': exit status 127
```
and 

```
Docker] [ERROR]
[Docker] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[Docker] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Docker] java.io.FileNotFoundException: ../*.jar (No such file or directory)
[Docker]        at java.io.FileInputStream.open0(Native Method)
[Docker]        at java.io.FileInputStream.open(FileInputStream.java:212)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:152)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:104)
[Docker]        at sun.tools.jar.Main.run(Main.java:319)
[Docker]        at sun.tools.jar.Main.main(Main.java:1300)
[Docker] The command '/bin/sh -c /project/util/check_version build  && /project/java-spring-boot2-build.sh package  && /project/java-spring-boot2-build.sh createStartScript' returned a non-zero code: 1
[Error] exit status 1
[Error] exit status 1
[Error] exit status 1
```

** Steps to reproduce the behavior: **
1. Clone stacks repo
2. Go to incubator/java-spring-boot2 directory
3. execute appsody stack validate command

**Environment Details :**
- OS: Linux
- ARCH: ppc64le
- Version: 0.3.22 
 - CLI version: appsody 0.5.8
 - Stack you are using (including the version): java-spring-boot2 0.3.23 or 0.3.22

PFA full log at - [appsody-validate-0.3.23.log](https://github.com/appsody/stacks/files/4181486/appsody-validate-0.3.23.log)

Any pointers in this regard would be of great help !

**Comment by vrushaliinamdar** [comment]
Hi,

Even after above change, the java-spring-boot2 stack kotlin template test and build validations are failing.
 **java-spring-boot2 stack - version 0.3.23**

@@@@@@@@@@@@@@@ Validate Summary Start @@@@@@@@@@@@@@@@
PASSED: Lint for stack:java-spring-boot2
PASSED: Package for stack:java-spring-boot2
PASSED: Init for stack:java-spring-boot2 template:default
PASSED: Run for stack:java-spring-boot2 template:default
PASSED: Test for stack:java-spring-boot2 template:default
PASSED: Build for stack:java-spring-boot2 template:default
PASSED: Init for stack:java-spring-boot2 template:kotlin
PASSED: Run for stack:java-spring-boot2 template:kotlin
FAILED: Test for stack:java-spring-boot2 template:kotlin
FAILED: Build for stack:java-spring-boot2 template:kotlin
Total PASSED: 8
Total FAILED: 2
@@@@@@@@@@@@@@@  Validate Summary End  @@@@@@@@@@@@@@@@

The error details are  - 
```
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/Hello.kt: (9, 17) Type mismatch: inferred type is kotlin.String but java.lang.String was expected
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/LivenessEndpoint.kt: (22, 2) Cannot access class 'java.lang.String'. Check your module classpath for missing or conflicting dependencies
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/LivenessEndpoint.kt: (22, 16) Type mismatch: inferred type is kotlin.String but java.lang.String was expected
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/LivenessEndpoint.kt: (23, 2) Cannot access class 'java.lang.String'. Check your module classpath for missing or conflicting dependencies
..
[Docker] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Docker] java.io.FileNotFoundException: ../*.jar (No such file or directory)
[Docker]        at java.io.FileInputStream.open0(Native Method)
[Docker]        at java.io.FileInputStream.open(FileInputStream.java:212)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:152)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:104)
[Docker]        at sun.tools.jar.Main.run(Main.java:319)
[Docker]        at sun.tools.jar.Main.main(Main.java:1300)
[Docker] The command '/bin/sh -c /project/util/check_version build  && /project/java-spring-boot2-build.sh package  && /project/java-spring-boot2-build.sh createStartScript' returned a non-zero code: 1
```

**However, if I use  java-spring-boot2 stack version 0.3.22, all the validations are passing.**

@@@@@@@@@@@@@@@ Validate Summary Start @@@@@@@@@@@@@@@@
PASSED: Lint for stack:java-spring-boot2-0.3.22
PASSED: Package for stack:java-spring-boot2-0.3.22
PASSED: Init for stack:java-spring-boot2-0.3.22 template:default
PASSED: Run for stack:java-spring-boot2-0.3.22 template:default
PASSED: Test for stack:java-spring-boot2-0.3.22 template:default
PASSED: Build for stack:java-spring-boot2-0.3.22 template:default
PASSED: Init for stack:java-spring-boot2-0.3.22 template:kotlin
PASSED: Run for stack:java-spring-boot2-0.3.22 template:kotlin
PASSED: Test for stack:java-spring-boot2-0.3.22 template:kotlin
PASSED: Build for stack:java-spring-boot2-0.3.22 template:kotlin
Total PASSED: 10
Total FAILED: 0
@@@@@@@@@@@@@@@  Validate Summary End  @@@@@@@@@@@@@@@@

Is there any specific change in version 0.3.23?

**Comment by CameronMcWilliam** [comment]
The volume for the controller isn’t being created as it should be, this is because of the `init-controller` image not supporting the ppc64le architecture, because the executable format is not recognised.  With your custom one you made, it worked but then failed later on the stack.  This is independent of the appsody init controller image and up to stack maintainers to use ppc64le compatible images.  Ozzy has opened a PR: https://github.com/appsody/stacks/pull/670 to add ppc64le support for the java-spring-boot2 stack and I will be pushing up a ppc64le arch init-controller image soon meaning you won’t have to use your own custom image.

**Comment by CameronMcWilliam** [comment]
We have released the controller to support both `s390x` and `ppc64le` architecture.  In order to use this controller, you can run `export APPSODY_CONTROLLER_VERSION=0.3.5`. 

**NOTE:** None of the Appsody stacks currently have Multi architecture support, so in order to use them, you will need to `git clone` the stack or run `appsody stack create` with the `--copy` flag, then run `stack package`.

**Comment by neeraj-laad** [comment]
CLI released with full support for p and z linux
