### ISSUE TITLE
HTTP_PROXY environment variable is not used. 

### ISSUE THREAD

**Issue by hygl** [appsody/appsody#90]
I want to use appsody behind a cooperate firewall and proxy chane. However environment variables like `HTTP_PROXY` are not used by the cli and there is no other way to configure a proxy for example in `.appsody.yaml` documented.

I would expect the `HTTP_PROXY` variable to work.
**version**: 0.2.5
**os**: ubuntu 18.04

output: `phuegelph@huegelph-HP-EliteDesk-800-G1-SFF:~/src/spring-boot-example$ appsody list
[Error] Failed to get repository index: Get https://raw.githubusercontent.com/appsody/stacks/master/index.yaml: dial tcp: lookup raw.githubusercontent.com: no such host
`

**Comment by chilanti** [comment]
The problem has to do with the fact that our code creates a new `&http.Transport{}` object - but doesn't set the `Proxy` (this is in `repo.go`).
