### ISSUE TITLE
Change of namespace for "appsody deploy" fails

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#910]
**Describe the bug**
I deployed an application to the default namespace, then to a different namespace, then attempted to deploy it again against the default namespace, which failed

**To Reproduce**
1. Assuming kubectl pointing to a valid cluster:
```
appsody init incubator/nodejs-express
appsody deploy
appsody deploy delete
appsody deploy -n istio-system
appsody delete
appsody deploy    << deploys against namespace istio-system, which may be a design decision
appsody delete
```
2. Attempt to put the application back in `default` namespace
```
appsody deploy -n default
```

**Expected behavior**
The application should be deployed against the Kubernetes "default" namespace

**Actual behaviour**
The application deployment failed with:
```
Found deployment manifest /Users/nastacio/github.com/icpa-opentracing/nodejs-tracing/app-deploy.yaml
[Error] the namespace "istio-system" from the deployment manifest does not match the namespace "default" passed as an argument.
```

**Environment Details (please complete the following information):**
 - OS: macOS Catalina

**If applicable please specify:**
 - CLI version: appsody 0.5.8
 - Stack you are using:
incubator/nodejs-express:0.4.2, though I don't think it matters

**Screenshots**
n/a

**Additional context**
Editing app-deploy.yaml and replacing `namespace: istio-system` with `namespace: default` worked around the problem.

**Comment by EnriqueL8** [comment]
We decided to go for the `kubectl` approach discussed in #464. 
If a user specifies a namespace arg and the deployment manifest does not contain a namespace value, we write that value passed to the deployment manifest to be used in subsequent calls to `appsody deploy`.

**Comment by nastacio** [comment]
The problem is not that design decision, it ia the fact that subsequent calls with a different namespace do not modify the value in the file and trigger an error.

This is a major problem if app-deploy.yaml is checked into git, which is often the case.
