### ISSUE TITLE
Paths in bind mounts on Win10 at certain Docker Desktop versions break many appsody commands

### ISSUE THREAD

**Issue by scottkurz** [appsody/appsody#912]
**Describe the bug**

At my level of Docker Desktop, the appsody commands using bind mounts:
 **init,  extract/build, run/debug/test** etc. (all of them?)
fail with errors like:  `[Container] docker: Error response from daemon: file does not exist.`

E.g.

> $ appsody test
> Running test environment
> Using local cache for image dev.local/appsody/java-openliberty:0.2
> Running command: docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name ol2e-dev -v C:/Users/ScottKurz/.m2/repository:/mvn/repository -v C:/ydosppa/apps/ol2e/.:/project/user-app -v appsody-controller-0.3.4:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/java-openliberty:0.2 --mode=test
> [Container] docker: Error response from daemon: file does not exist.
> [Container] See 'docker run --help'.
> [Error] Error in 'appsody test': exit status 125
> 
> 

**To Reproduce**

Simply do
* `appsody init java-openliberty`     (you see the problem as a warning but you could ignore and continue)
* `appsody run`

**Environment Details (please complete the following information):**
 - OS: Win 10 Build 1903
- Docker Desktop v2.2.0.3

**If applicable please specify:**
 - appsody CLI v0.5.8
 - Stack you are using: java-openliberty

**Additional context**
Naturally I'd like to know how was this working before for me on Win10?

I believe I was on  Docker Desktop Edge v2.1.7.0 when it worked at the same level of appsody

**Workaround**

Each individual Docker command can be "fixed" manually by adjusting the bind mount path to remove the "dot-slash" (./), e.g.:

Change:
`docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name ol2e-dev -v C:/Users/ScottKurz/.m2/repository:/mvn/repository -v C:/ydosppa/apps/ol2e/.:/project/user-app ....`
to:
`docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name ol2e-dev -v C:/Users/ScottKurz/.m2/repository:/mvn/repository -v C:/ydosppa/apps/ol2e:/project/user-app ....`

Of course, this doesn't help for `appsody build`

**Comment by scottkurz** [comment]
Workaround [here](https://github.com/scottkurz/appsody/tree/debug-win).... my first Go code

**Comment by timroster** [comment]
Similar issues here with Windows 10 Build 1909

**Comment by timroster** [comment]
Not seeing this with all stacks. `nodejs-express` seems unaffected:

```
Running command: docker run --rm -p 3000:3000 -p 9229:9229 --name foobar-dev -v C:/UsersRunning command: docker run --rm -p 3000:3000 -p 9229:9229 --name foobar-dev -v C:/Users/TimRobinson/appsody-apps/foobar/:/project/user-app -v foobar-deps:/project/user-app/node_modules -v appsody-controller-0.3.4:/.appsody -t --entrypoint /.appsody/appsody-controller docker.io/appsody/nodejs-express:0.4 --mode=run
```
