### ISSUE TITLE
Avoid conflicts between Appsody docker volumes

### ISSUE THREAD

**Issue by groeges** [appsody/appsody#926]
**Describe the bug**
When an Apposdy projects is created and run, if the Dockerfile-stack has an APPSODY_DEPS entry, a docker volume is created using the project name prepended with -deps as the volume name. e.g. if I have a project directory called `myproject`, which contains a nodejs-express stack, the volume is created as `myproject-deps`. This is all OK and everything works OK using this volume. 

However if I delete the project and create a new project using the same directory, possibly using a different stack, ie kitura, the same docker volume is used. 

The reuse of this docker volume may cause (has caused) issues due to incompatible data stored in the volume. We have seen this issue where one stack runs as root and creates data in the volume  owned by root, then the 2nd project doesn't run as root and has issues accessing the files in the volume.

**Expected behavior**
Creation and execution of an Appsody project that can run successfully, even if it has been named the same as a previous project.
 
**Actual behaviour**
Issues due to incompatibilities in content of volumes

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by skoh7645** [comment]
This should be implemented after https://github.com/appsody/appsody/issues/938.

On every `appsody init`:
 - Loop through the contents stored in the `~/.appsody/project.yaml` file. For every project, check `/absolute/path/to/project/.appsody-config.yaml` exists. 
 - If is does not exist, delete the project entry and all volumes listed. 
 - If the file exists, check the value of `id` in `/absolute/path/to/project/.appsody-config.yaml` is the same as that in `~/.appsody/project.yaml`. 
 - If `id` is not the same, delete the project entry and all volumes listed

**Comment by makandre** [comment]
Hi @skoh7645, here's another scenario/usage to consider:

When using Codewind, users can delete an appsody project.  Currently we will also clean up the deps volume by calling `docker volume rm` on it.

With changes proposed here (and in #938), Codewind will need to know the new naming scheme used for the multiple deps volumes so we can remove them accordingly.  (But entries in `project.yaml` file will remain)

Alternatively it would be nice to have a command for us to call to do this cleanup; it's weird for Codewind to call `appsody init` to get this cleanup behaviour when we know which project is being deleted.
