### ISSUE TITLE
Stop adding "-dev" to hostnames during "application run"

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#932]
**Is your feature request related to a problem? Please describe.**
Appsody applications are primarily meant to be deployed to Kubernetes clusters, but during development the containers have different hostnames with `appsody run` and `appsody deploy`.

`appsody run` creates containers with hostname "<applicationName>-dev" whereas `appsody deploy` creates containers with hostname "<applicationName>", which is an endless source of breakage when working with multiple microservices in the same environment.

The ensuing errors can be worked around by using the `--name <applicationName>` when invoking `appsody run`, but that is cumbersome and only becomes apparent after users have spent time troubleshooting error messages containing some framework-specific variation of [host not found].

**To Reproduce**
1. Create the docker network for connecting the two services about to be created:
```
docker network create test_network
```

2. From one terminal window
```
mkdir nodejs-a
cd nodejs-a
appsody init incubator/nodejs-express
appsody run --network test_network
```

3. From another terminal window
```
mkdir nodejs-b
cd nodejs-b
appsody init incubator/nodejs-express
appsody run -p "3001:3000" -p "9230:9229" --network test_network
```

Wait until both applications are up, then issue these two commands from a third terminal window:
```
docker exec -it  nodejs-a-dev /bin/sh -c "ping -c 1 nodejs-b"
ping: nodejs-b: Name or service not known
```

**Describe the solution you'd like**
The hostname for an application in the development environment should be same whether the application is launched directly from `appsody run` or indirectly from `appsody deploy`

**Actual behaviour**
The hostname for the applications launched with `appsody run` has "-dev" tacked on to the end of their name, for no apparent reason. Host lookup code that works in development will not work inside a Kubernetes cluster unless you always modify the hostname 

**Describe alternatives you've considered**
1. One could always write code that retrieves hostnames from environment variables, which seems like a good practice, but a good practice is not meant to be mandatory otherwise it is a hard requirement.

2. Always rename the host/container in `appsody run` with `--name <desired_hostname>`

**Comment by neeraj-laad** [comment]
@chilanti Was there any apparent reason for using `-dev` during local `appsody run`?
