### ISSUE TITLE
By default, set spec.createAppDefinition: true

### ISSUE THREAD

**Issue by dacleyra** [appsody/appsody#942]
**Is your feature request related to a problem? Please describe.**

Application projects deployments generated by `appsody deploy --generate-only` have neither the AppsodyApplication spec.createAppDefinition defined, nor it preferably set to true.

**Comment by neeraj-laad** [comment]
@leochr I thought the operator was looking to change the way micro-service to application relationship was described and handled by the operator.  Possibly by using k8s part-of label?

Please can you confirm.

**Comment by leochr** [comment]
In Appsody operator (as well as Runtime Component and Open Liberty operators), the default value for `spec.createAppDefinition` is `true`. We recently added `applicationName` field which uses the `app.kubernetes.io/part-of` label to bind to an existing Application definition - or set the auto-create labels for kAppNav. It's documented [here](https://github.com/application-stacks/runtime-component-operator/blob/eba267c29b86b16ec59954ac2042b3821ec5938f/doc/user-guide.md#kubernetes-application-navigator-kappnav-support)

**Comment by neeraj-laad** [comment]
Thanks @leochr 

@dacleyra I'm closing this but if you feel there is still more work on this please feel free to re-open.
