### ISSUE TITLE
Add stack image digest as a label on application image

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#957]
Appsody adds traceability labels to indicate which stack version is used to build the stack. However, we use the tag as a way to uniquely identify the stack image
```
"dev.appsody.stack.tag": "docker.io/appsody/nodejs-express:0.4.5"
```

We would like to see the actual image digest for the image added as an additional label. I did not find an OCI spec label for this, so suggesting we use: 

```
"dev.appsody.stack.digest": "<image digest>"
```

**Comment by EnriqueL8** [comment]
Reopening issue as we are reverting this change. 

Buildah path not working yet. See: https://github.com/containers/buildah/issues/2074
