### ISSUE TITLE
Support appsody on K8S

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#96]
**Is your feature request related to a problem? Please describe.**
Appsody currently cannot run in a K8S cluster, which prevents it from being available as an on-cloud solution (like Eclipse Che). 

**Describe the solution you'd like**
Allow Appsody to run as a docker-in-docker solution. 

**Describe alternatives you've considered**
None.

**Additional context**
This request comes primarily from the Codewind dev team.
The fundamental problem that needs to be resolved for Appsody to fully run on K8S is that of the Docker mount points. Currently, there's the https://github.com/appsody/appsody-docker image which does provide some level of Appsody functionality (it can successfully run `appsody extract`, `appsody init <stack>` for example). However, commands like `appsody run` will not work, because the volumes that are bind mounted by the docker-in-docker daemon are expected to be located on the host's file system.

**Comment by kylegc** [comment]
In order to support this, we will probably have to get fancy with shared docker volumes instead of filesystem bind mounts. However, this is a fundamental design change for Appsody which will need a lot of discussion, design, coding, and testing.

Making this an Epic.

**Comment by makandre** [comment]
Also, on k8s there will not be a docker daemon.
