### ISSUE TITLE
Error when running `appsody build` on Windows.

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody#973]
**Describe the bug**
When running appsody build, we get the following error:
```
[Warning] The stack image does not contain APPSODY_PROJECT_DIR. Using /project
Running command: docker run --name <name> -v <volumes> --entrypoint /bin/bash docker.io/appsody/java-openliberty:0.1 -c cp -rfL /project /tmp/project
Running command: docker rm <name>
[Warning] Ignoring container remove error Error running docker command: exit status 1
[Error] Error attempting to run copy command cp -rfL /project /tmp/project on image docker.io/appsody/java-openliberty:0.1: exit status 125
```

After some investigation, we had to replace `/bin/bash` with `bash` or we could switch it to `sh`.

**To Reproduce**
1. Run appsody build in a windows machine with the OpenLiberty stack.

**Environment Details (please complete the following information):**
 - OS: Windows
 - CLI version: 0.5.9
 - Stack you are using: OpenLiberty 0.2.x
 - Terminal: `git bash`

**Comment by Cottonglow** [comment]
This might be part of the issue - https://github.com/docker/for-win/issues/6016

**Comment by djones6** [comment]
The Docker Desktop for Windows v2.2.0.4 issue results in a slightly different return code:
```
Running command: docker rm appsody-proj-extract -f
[Error] Error attempting to run copy command cp -rfL /project /tmp/project on image docker.io/appsody/java-spring-boot2:0.3: exit status 1
```
For some reason we don't get the logs for the `cp` command, even with `appsody build -v`.  (which probably warrants a separate investigation?)

If I manually recreate the command that fails, it's because of read-only files in the `.git` directory that are inaccessible (due to the bug mentioned above):
```
java_user@d5750b818c51:/project/user-app$ cp -rfL /project /tmp/project
cp: cannot open '/project/user-app/.git/objects/d9/de97b2cfee94e84bdb7690a156896bb8310afb' for reading: Operation not permitted
(etc)
```

**Comment by djones6** [comment]
FYI, Docker Desktop 2.2.0.5 has just been released which resolves the Windows read-only files issue.

**Comment by EnriqueL8** [comment]
@djones6 do you think we can close this issue then?

**Comment by Cottonglow** [comment]
Updating to the latest appsody and docker desktop versions has resolved my issues, so happy to close it on my end.
