### ISSUE TITLE
The doc page for environment variables returns 404

### ISSUE THREAD

**Issue by sriniketana** [appsody/appsody#978]
**Describe the bug**
The doc page for stack environment variables returns a 404
https://appsody.dev/docs/stacks/environment-variables

**To Reproduce**
Open https://appsody.dev/docs/stacks/environment-variables in a browser 

**Expected behavior**
A redirect to https://appsody.dev/docs/reference/environment-variables/ should be in plaec 

**Actual behaviour**
Page returns a 404

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by helenmasters** [comment]
@ddunn2 please can you take a look at this for me?

**Comment by skoh7645** [comment]
I've just opened a PR for this! :)
