### ISSUE TITLE
Indicate a deprecated stack in the Codewind JSON

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#983]
**Is your feature request related to a problem? Please describe.**
Since stack maintainers can now deprecate a stack, we indicate deprecated stacks in the generated `repo-index.yaml`. This information should be reflected in the Codewind JSON file we generate so Codewind users are also warned that a stack is being deprecated.

**Describe the solution you'd like**
Indicate this by appending a new field `deprecated: true`, in the generated Codewind JSON if the stack is deprecated

**Describe alternatives you've considered**
Indicate this by prepending [Deprecated] to the  `displayName` field, if a stack is deprecated

**Comment by makandre** [comment]
An extra field on the index should be fine for Codewind.  And I think **also** doing the alternative solution at the same time is a good idea to make it visible in Codewind right away.

**Comment by neeraj-laad** [comment]
Might be best to pass on the same field/value as we have in appsody index.yaml.

Will need a change in Appsody CLI (stack package) and perhaps also in stack/repo-tools CI (if we are still using the python script)

**Comment by groeges** [comment]
The appsody/repo-tools  uses the create_codewind_index.py (https://github.com/appsody/repo-tools/blob/master/scripts/create_codewind_index.py) and this will need to be able to add the additional deprecated flag to the *-index.json file if it exists within the *-index.yaml

Once this is done then there are other repos that use the same tooling: 
https://github.com/kabanero-io/kabanero-stack-hub/blob/master/scripts/create_codewind_index.py

these will also need to be updated to pull in this change.  
Please inform me when this work has been done and I can make the changes int he other repos.
