### ISSUE TITLE
Review all labels and annotations relating to personal information

### ISSUE THREAD

**Issue by skoh7645** [appsody/appsody#987]
There could be a potential privacy issue when it comes to including a stack maintainer's or commiter's personal information in the stack/application image labels or on deployment manifests. 

We should review (and possibly remove) the following:

**Stack image labels:**
- [ ] `dev.appsody.image.commit.author` 
- [ ] `dev.appsody.image.commit.committer`
- [ ] `org.opencontainers.image.authors`

**Application image labels:**
- [ ] `dev.appsody.image.commit.author` 
- [ ] `dev.appsody.image.commit.committer`
- [ ] `dev.appsody.stack.authors`
- [ ] `dev.appsody.stack.commit.author`
- [ ] `dev.appsody.stack.commit.committer`
- [ ] `org.opencontainers.image.authors`

**Application Deployment labels/annotations:**
- [ ] `dev.appsody.image.commit.author` 
- [ ] `dev.appsody.image.commit.committer`
- [ ] `dev.appsody.stack.authors`
- [ ] `dev.appsody.stack.commit.author`
- [ ] `dev.appsody.stack.commit.committer`
- [ ] `org.opencontainers.image.authors`

**Comment by CameronMcWilliam** [comment]
Some initial thoughts:

- Also need to think about including personal info on an Appsody applications when using `appsody build` 
- Some `org.opencontainers` labels are the same labels as the `dev.appsody` labels, they change prefix in the build stage see https://appsody.dev/docs/reference/metadata
- Maybe removing emails could be a step?  Unsure if we need to remove labels entirely if we just don't include emails, I personally feel like names could be ok? What do others think of that?

**Comment by neeraj-laad** [comment]
Updated the main description to reflect the 3 areas we should cover.
