### ISSUE TITLE
Appsody debug does not use "npm run debug" on k8s [codewind]

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#999]
**Describe the bug**

Discovered while testing https://github.com/appsody/appsody/pull/994 with instructions provider therein.

When running `appsody debug` on `APPSODY_K8S_EXPERIMENTAL=TRUE` path, it appears within the app it runs `npm start` rather than `npm run debug`.  Hence, the container isn't actually listening on the debug port.

I don't know if this is a CLI problem or an issue with the `node-express` stack, tho it's possible `appsody debug` has never worked on this path before; Codewind has only used `appsody run` on k8s in the past.

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by makandre** [comment]
Log with verbose

[appsody.log](https://github.com/appsody/appsody/files/4659258/appsody.log)

**Comment by neeraj-laad** [comment]
@makandre We only support `appsody run` on K8S. None of the other scenarios was supported. 

I suspect this will be true for all the stacks and is working as designed.

Related issue: https://github.com/appsody/appsody/issues/561

I'm closing this issue and we should look at the main issue if we need appsody debug to work on K8S. What about `appsody test`?

**Comment by makandre** [comment]
@neeraj-laad Thanks for the info.  We are not using `appsody test` at the moment in Codewind (neither local or k8s)
